/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103745Module"
 * 	found in "preprocessed_temp/EtsiTs103745Module.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/RMO_TS_103_745/Gen_File`
 */

#ifndef	_EllipticalRegion_H_
#define	_EllipticalRegion_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GeoPositionWoAltitude.h"
#include "SimpleEllipticalShape.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EllipticalRegion */
typedef struct EllipticalRegion {
	GeoPositionWoAltitude_t	 center;
	SimpleEllipticalShape_t	 ellipticalShape;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EllipticalRegion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EllipticalRegion;
extern asn_SEQUENCE_specifics_t asn_SPC_EllipticalRegion_specs_1;
extern asn_TYPE_member_t asn_MBR_EllipticalRegion_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EllipticalRegion_H_ */
#include <asn_internal.h>
