/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103745Module"
 * 	found in "preprocessed_temp/EtsiTs103745Module.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/RMO_TS_103_745/Gen_File`
 */

#ifndef	_Rmo_H_
#define	_Rmo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RmoClass.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InterferenceManagementChannel;

/* Rmo */
typedef struct Rmo {
	RmoClass_t	 rmoClass;
	struct InterferenceManagementChannel	*restrictedChannel;	/* OPTIONAL */
	long	*limit;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Rmo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Rmo;
extern asn_SEQUENCE_specifics_t asn_SPC_Rmo_specs_1;
extern asn_TYPE_member_t asn_MBR_Rmo_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InterferenceManagementChannel.h"

#endif	/* _Rmo_H_ */
#include <asn_internal.h>
