/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103745Module"
 * 	found in "preprocessed_temp/EtsiTs103745Module.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/RMO_TS_103_745/Gen_File`
 */

#ifndef	_RmoClass_H_
#define	_RmoClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RmoClass {
	RmoClass_noTx	= 0,
	RmoClass_eirp	= 1,
	RmoClass_allowedOnPeriods	= 2
	/*
	 * Enumeration is extensible
	 */
} e_RmoClass;

/* RmoClass */
typedef long	 RmoClass_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RmoClass_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RmoClass;
extern const asn_INTEGER_specifics_t asn_SPC_RmoClass_specs_1;
asn_struct_free_f RmoClass_free;
asn_struct_print_f RmoClass_print;
asn_constr_check_f RmoClass_constraint;
ber_type_decoder_f RmoClass_decode_ber;
der_type_encoder_f RmoClass_encode_der;
xer_type_decoder_f RmoClass_decode_xer;
xer_type_encoder_f RmoClass_encode_xer;
jer_type_encoder_f RmoClass_encode_jer;
oer_type_decoder_f RmoClass_decode_oer;
oer_type_encoder_f RmoClass_encode_oer;
per_type_decoder_f RmoClass_decode_uper;
per_type_encoder_f RmoClass_encode_uper;
per_type_decoder_f RmoClass_decode_aper;
per_type_encoder_f RmoClass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RmoClass_H_ */
#include <asn_internal.h>
