/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103745Module"
 * 	found in "preprocessed_temp/EtsiTs103745Module.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/RMO_TS_103_745/Gen_File`
 */

#ifndef	_RmoRegionIdentifier_H_
#define	_RmoRegionIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RmoRegionIdentifier */
typedef unsigned long	 RmoRegionIdentifier_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RmoRegionIdentifier_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RmoRegionIdentifier;
extern const asn_INTEGER_specifics_t asn_SPC_RmoRegionIdentifier_specs_1;
asn_struct_free_f RmoRegionIdentifier_free;
asn_struct_print_f RmoRegionIdentifier_print;
asn_constr_check_f RmoRegionIdentifier_constraint;
ber_type_decoder_f RmoRegionIdentifier_decode_ber;
der_type_encoder_f RmoRegionIdentifier_encode_der;
xer_type_decoder_f RmoRegionIdentifier_decode_xer;
xer_type_encoder_f RmoRegionIdentifier_encode_xer;
jer_type_encoder_f RmoRegionIdentifier_encode_jer;
oer_type_decoder_f RmoRegionIdentifier_decode_oer;
oer_type_encoder_f RmoRegionIdentifier_encode_oer;
per_type_decoder_f RmoRegionIdentifier_decode_uper;
per_type_encoder_f RmoRegionIdentifier_encode_uper;
per_type_decoder_f RmoRegionIdentifier_decode_aper;
per_type_encoder_f RmoRegionIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RmoRegionIdentifier_H_ */
#include <asn_internal.h>
