/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103745Module"
 * 	found in "preprocessed_temp/EtsiTs103745Module.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/RMO_TS_103_745/Gen_File`
 */

#ifndef	_RmoZone_H_
#define	_RmoZone_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ItsStationType.h"
#include "RmoRegionIdentifier.h"
#include "TimestampIts.h"
#include "SequenceOfRmo.h"
#include "InterferenceManagementZoneType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InterferenceManagementChannel;

/* RmoZone */
typedef struct RmoZone {
	ItsStationType_t	*itsStationType;	/* OPTIONAL */
	struct InterferenceManagementChannel	*interfererChannel;	/* OPTIONAL */
	RmoRegionIdentifier_t	 rmoRegionIdentifier;
	TimestampIts_t	 rmoActivationDate;
	TimestampIts_t	*rmoExpiryDate;	/* OPTIONAL */
	SequenceOfRmo_t	 sequenceOfRmo;
	InterferenceManagementZoneType_t	*interferenceManagementZoneType;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RmoZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RmoZone;
extern asn_SEQUENCE_specifics_t asn_SPC_RmoZone_specs_1;
extern asn_TYPE_member_t asn_MBR_RmoZone_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InterferenceManagementChannel.h"

#endif	/* _RmoZone_H_ */
#include <asn_internal.h>
