/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103745Module"
 * 	found in "preprocessed_temp/EtsiTs103745Module.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/RMO_TS_103_745/Gen_File`
 */

#ifndef	_SequenceOfGeographicRegion_H_
#define	_SequenceOfGeographicRegion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GeographicRegion;

/* SequenceOfGeographicRegion */
typedef struct SequenceOfGeographicRegion {
	A_SEQUENCE_OF(struct GeographicRegion) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfGeographicRegion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfGeographicRegion;
extern asn_SET_OF_specifics_t asn_SPC_SequenceOfGeographicRegion_specs_1;
extern asn_TYPE_member_t asn_MBR_SequenceOfGeographicRegion_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeographicRegion.h"

#endif	/* _SequenceOfGeographicRegion_H_ */
#include <asn_internal.h>
