/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "preprocessed_temp/AVM-Commons.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_AvmE2EProtection_H_
#define	_AvmE2EProtection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UInt16.h"
#include "UInt32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AvmE2EProtection */
typedef struct AvmE2EProtection {
	UInt16_t	 length;
	UInt16_t	 rollingCounter;
	UInt32_t	 dataID;
	UInt32_t	 crc32;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AvmE2EProtection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AvmE2EProtection;
extern asn_SEQUENCE_specifics_t asn_SPC_AvmE2EProtection_specs_1;
extern asn_TYPE_member_t asn_MBR_AvmE2EProtection_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _AvmE2EProtection_H_ */
#include <asn_internal.h>
