/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_ControlInterface_H_
#define	_ControlInterface_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PathControl.h"
#include "TrajectoryControl.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ControlInterface_PR {
	ControlInterface_PR_NOTHING,	/* No components present */
	ControlInterface_PR_pathControl,
	ControlInterface_PR_trajectoryControl
	/* Extensions may appear below */
	
} ControlInterface_PR;

/* ControlInterface */
typedef struct ControlInterface {
	ControlInterface_PR present;
	union {
		PathControl_t	 pathControl;
		TrajectoryControl_t	 trajectoryControl;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	};
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ControlInterface_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ControlInterface;
extern asn_CHOICE_specifics_t asn_SPC_ControlInterface_specs_1;
extern asn_TYPE_member_t asn_MBR_ControlInterface_1[2];
extern asn_per_constraints_t asn_PER_type_ControlInterface_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ControlInterface_H_ */
#include <asn_internal.h>
