/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_ControlAcceleration_H_
#define	_ControlAcceleration_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LongitudinalAccelerationValue.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ControlAcceleration */
typedef LongitudinalAccelerationValue_t	 ControlAcceleration_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ControlAcceleration_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ControlAcceleration;
asn_struct_free_f ControlAcceleration_free;
asn_struct_print_f ControlAcceleration_print;
asn_constr_check_f ControlAcceleration_constraint;
ber_type_decoder_f ControlAcceleration_decode_ber;
der_type_encoder_f ControlAcceleration_encode_der;
xer_type_decoder_f ControlAcceleration_decode_xer;
xer_type_encoder_f ControlAcceleration_encode_xer;
jer_type_encoder_f ControlAcceleration_encode_jer;
oer_type_decoder_f ControlAcceleration_decode_oer;
oer_type_encoder_f ControlAcceleration_encode_oer;
per_type_decoder_f ControlAcceleration_decode_uper;
per_type_encoder_f ControlAcceleration_encode_uper;
per_type_decoder_f ControlAcceleration_decode_aper;
per_type_encoder_f ControlAcceleration_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ControlAcceleration_H_ */
#include <asn_internal.h>
