/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "preprocessed_temp/AVM-Commons.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_Description_H_
#define	_Description_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Description */
typedef IA5String_t	 Description_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Description_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Description;
asn_struct_free_f Description_free;
asn_struct_print_f Description_print;
asn_constr_check_f Description_constraint;
ber_type_decoder_f Description_decode_ber;
der_type_encoder_f Description_encode_der;
xer_type_decoder_f Description_decode_xer;
xer_type_encoder_f Description_encode_xer;
jer_type_encoder_f Description_encode_jer;
oer_type_decoder_f Description_decode_oer;
oer_type_encoder_f Description_encode_oer;
per_type_decoder_f Description_decode_uper;
per_type_encoder_f Description_encode_uper;
per_type_decoder_f Description_decode_aper;
per_type_encoder_f Description_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Description_H_ */
#include <asn_internal.h>
