/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_EmergencyStopEnum_H_
#define	_EmergencyStopEnum_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EmergencyStopEnum {
	EmergencyStopEnum_inactive	= 0,
	EmergencyStopEnum_precharge	= 1,
	EmergencyStopEnum_active	= 2,
	EmergencyStopEnum_tempError	= 3,
	EmergencyStopEnum_suspend	= 4
} e_EmergencyStopEnum;

/* EmergencyStopEnum */
typedef long	 EmergencyStopEnum_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EmergencyStopEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EmergencyStopEnum;
extern const asn_INTEGER_specifics_t asn_SPC_EmergencyStopEnum_specs_1;
asn_struct_free_f EmergencyStopEnum_free;
asn_struct_print_f EmergencyStopEnum_print;
asn_constr_check_f EmergencyStopEnum_constraint;
ber_type_decoder_f EmergencyStopEnum_decode_ber;
der_type_encoder_f EmergencyStopEnum_encode_der;
xer_type_decoder_f EmergencyStopEnum_decode_xer;
xer_type_encoder_f EmergencyStopEnum_encode_xer;
jer_type_encoder_f EmergencyStopEnum_encode_jer;
oer_type_decoder_f EmergencyStopEnum_decode_oer;
oer_type_encoder_f EmergencyStopEnum_encode_oer;
per_type_decoder_f EmergencyStopEnum_decode_uper;
per_type_encoder_f EmergencyStopEnum_encode_uper;
per_type_decoder_f EmergencyStopEnum_decode_aper;
per_type_encoder_f EmergencyStopEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EmergencyStopEnum_H_ */
#include <asn_internal.h>
