/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "preprocessed_temp/AVM-Commons.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_GearEnum_H_
#define	_GearEnum_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GearEnum {
	GearEnum_park	= 0,
	GearEnum_backwards	= 1,
	GearEnum_neutral	= 2,
	GearEnum_forwards	= 3,
	GearEnum_unknown	= 4
} e_GearEnum;

/* GearEnum */
typedef long	 GearEnum_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_GearEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_GearEnum;
extern const asn_INTEGER_specifics_t asn_SPC_GearEnum_specs_1;
asn_struct_free_f GearEnum_free;
asn_struct_print_f GearEnum_print;
asn_constr_check_f GearEnum_constraint;
ber_type_decoder_f GearEnum_decode_ber;
der_type_encoder_f GearEnum_encode_der;
xer_type_decoder_f GearEnum_decode_xer;
xer_type_encoder_f GearEnum_encode_xer;
jer_type_encoder_f GearEnum_encode_jer;
oer_type_decoder_f GearEnum_decode_oer;
oer_type_encoder_f GearEnum_encode_oer;
per_type_decoder_f GearEnum_decode_uper;
per_type_encoder_f GearEnum_encode_uper;
per_type_decoder_f GearEnum_decode_aper;
per_type_encoder_f GearEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _GearEnum_H_ */
#include <asn_internal.h>
