/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "preprocessed_temp/AVM-Commons.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_Int16_H_
#define	_Int16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Int16 */
typedef long	 Int16_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Int16_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Int16;
asn_struct_free_f Int16_free;
asn_struct_print_f Int16_print;
asn_constr_check_f Int16_constraint;
ber_type_decoder_f Int16_decode_ber;
der_type_encoder_f Int16_encode_der;
xer_type_decoder_f Int16_decode_xer;
xer_type_encoder_f Int16_encode_xer;
jer_type_encoder_f Int16_encode_jer;
oer_type_decoder_f Int16_decode_oer;
oer_type_encoder_f Int16_encode_oer;
per_type_decoder_f Int16_decode_uper;
per_type_encoder_f Int16_encode_uper;
per_type_decoder_f Int16_decode_aper;
per_type_encoder_f Int16_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Int16_H_ */
#include <asn_internal.h>
