/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#include "InterlockEnum.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_InterlockEnum_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_InterlockEnum_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_InterlockEnum_value2enum_1[] = {
	{ 0,	4,	"none" },
	{ 1,	14,	"zonalInterlock" },
	{ 2,	10,	"globalStop" }
};
static const unsigned int asn_MAP_InterlockEnum_enum2value_1[] = {
	2,	/* globalStop(2) */
	0,	/* none(0) */
	1	/* zonalInterlock(1) */
};
const asn_INTEGER_specifics_t asn_SPC_InterlockEnum_specs_1 = {
	asn_MAP_InterlockEnum_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_InterlockEnum_enum2value_1,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_InterlockEnum_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_InterlockEnum = {
	"InterlockEnum",
	"InterlockEnum",
	&asn_OP_NativeEnumerated,
	asn_DEF_InterlockEnum_tags_1,
	sizeof(asn_DEF_InterlockEnum_tags_1)
		/sizeof(asn_DEF_InterlockEnum_tags_1[0]), /* 1 */
	asn_DEF_InterlockEnum_tags_1,	/* Same as above */
	sizeof(asn_DEF_InterlockEnum_tags_1)
		/sizeof(asn_DEF_InterlockEnum_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_InterlockEnum_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_InterlockEnum_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_InterlockEnum_specs_1	/* Additional specs */
};

