/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MVM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MVM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#include "OperationModeEnum.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_OperationModeEnum_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_OperationModeEnum_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  8 }	/* (0..8,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_OperationModeEnum_value2enum_1[] = {
	{ 0,	7,	"unknown" },
	{ 1,	12,	"initializing" },
	{ 2,	8,	"prepared" },
	{ 3,	7,	"driving" },
	{ 4,	11,	"terminating" },
	{ 5,	7,	"suspend" },
	{ 6,	9,	"tempError" },
	{ 7,	14,	"humanInControl" },
	{ 8,	11,	"stationHold" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_OperationModeEnum_enum2value_1[] = {
	3,	/* driving(3) */
	7,	/* humanInControl(7) */
	1,	/* initializing(1) */
	2,	/* prepared(2) */
	8,	/* stationHold(8) */
	5,	/* suspend(5) */
	6,	/* tempError(6) */
	4,	/* terminating(4) */
	0	/* unknown(0) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_OperationModeEnum_specs_1 = {
	asn_MAP_OperationModeEnum_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_OperationModeEnum_enum2value_1,	/* N => "tag"; sorted by N */
	9,	/* Number of elements in the maps */
	10,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_OperationModeEnum_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_OperationModeEnum = {
	"OperationModeEnum",
	"OperationModeEnum",
	&asn_OP_NativeEnumerated,
	asn_DEF_OperationModeEnum_tags_1,
	sizeof(asn_DEF_OperationModeEnum_tags_1)
		/sizeof(asn_DEF_OperationModeEnum_tags_1[0]), /* 1 */
	asn_DEF_OperationModeEnum_tags_1,	/* Same as above */
	sizeof(asn_DEF_OperationModeEnum_tags_1)
		/sizeof(asn_DEF_OperationModeEnum_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_OperationModeEnum_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_OperationModeEnum_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_OperationModeEnum_specs_1	/* Additional specs */
};

