/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_PathControl_H_
#define	_PathControl_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Centimetre.h"
#include "VelocityComponentValue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PathSnippet;

/* PathControl */
typedef struct PathControl {
	struct PathSnippet	*pathSnippet;	/* OPTIONAL */
	Centimetre_t	 clearedDistanceOnPath;
	VelocityComponentValue_t	*situationalVelocityLimit;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PathControl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathControl;
extern asn_SEQUENCE_specifics_t asn_SPC_PathControl_specs_1;
extern asn_TYPE_member_t asn_MBR_PathControl_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PathSnippet.h"

#endif	/* _PathControl_H_ */
#include <asn_internal.h>
