/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "preprocessed_temp/AVM-Commons.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_SafetyViolationsEnum_H_
#define	_SafetyViolationsEnum_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SafetyViolationsEnum {
	SafetyViolationsEnum_noViolation	= 0,
	SafetyViolationsEnum_noDrivingPermissionReceived	= 1,
	SafetyViolationsEnum_lastDrivingPermissionTooOld	= 2,
	SafetyViolationsEnum_crcViolationClockSyncRequest	= 3,
	SafetyViolationsEnum_crcViolationDrivingPermission	= 4,
	SafetyViolationsEnum_expirationTimeViolation	= 5,
	SafetyViolationsEnum_drivingDirectionMismatch	= 6,
	SafetyViolationsEnum_velocityViolation	= 7,
	SafetyViolationsEnum_curvatureMinViolation	= 8,
	SafetyViolationsEnum_curvatureMaxViolation	= 9,
	SafetyViolationsEnum_expirationTimeTooHigh	= 10,
	SafetyViolationsEnum_monitoring	= 11
	/*
	 * Enumeration is extensible
	 */
} e_SafetyViolationsEnum;

/* SafetyViolationsEnum */
typedef long	 SafetyViolationsEnum_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SafetyViolationsEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SafetyViolationsEnum;
extern const asn_INTEGER_specifics_t asn_SPC_SafetyViolationsEnum_specs_1;
asn_struct_free_f SafetyViolationsEnum_free;
asn_struct_print_f SafetyViolationsEnum_print;
asn_constr_check_f SafetyViolationsEnum_constraint;
ber_type_decoder_f SafetyViolationsEnum_decode_ber;
der_type_encoder_f SafetyViolationsEnum_encode_der;
xer_type_decoder_f SafetyViolationsEnum_decode_xer;
xer_type_encoder_f SafetyViolationsEnum_encode_xer;
jer_type_encoder_f SafetyViolationsEnum_encode_jer;
oer_type_decoder_f SafetyViolationsEnum_decode_oer;
oer_type_encoder_f SafetyViolationsEnum_encode_oer;
per_type_decoder_f SafetyViolationsEnum_decode_uper;
per_type_encoder_f SafetyViolationsEnum_encode_uper;
per_type_decoder_f SafetyViolationsEnum_decode_aper;
per_type_encoder_f SafetyViolationsEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SafetyViolationsEnum_H_ */
#include <asn_internal.h>
