/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_SafetyTimeSyncRequest_H_
#define	_SafetyTimeSyncRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UInt16.h"
#include "UInt32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SafetyTimeSyncRequest */
typedef struct SafetyTimeSyncRequest {
	UInt16_t	 challenge;
	UInt32_t	 checksum;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SafetyTimeSyncRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SafetyTimeSyncRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_SafetyTimeSyncRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_SafetyTimeSyncRequest_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SafetyTimeSyncRequest_H_ */
#include <asn_internal.h>
