/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MVM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MVM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_SafetyTimeSyncResponse_H_
#define	_SafetyTimeSyncResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UInt16.h"
#include "TimestampIts.h"
#include "UInt32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SafetyTimeSyncResponse */
typedef struct SafetyTimeSyncResponse {
	UInt16_t	 challenge;
	TimestampIts_t	 vehicleSafetyClockReceiveTimestamp;
	TimestampIts_t	 vehicleSafetyClockTransmitTimestamp;
	UInt32_t	 checksum;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SafetyTimeSyncResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SafetyTimeSyncResponse;
extern asn_SEQUENCE_specifics_t asn_SPC_SafetyTimeSyncResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_SafetyTimeSyncResponse_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SafetyTimeSyncResponse_H_ */
#include <asn_internal.h>
