/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "preprocessed_temp/AVM-Commons.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_SessionMissionID_H_
#define	_SessionMissionID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SessionMissionID */
typedef IA5String_t	 SessionMissionID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SessionMissionID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SessionMissionID;
asn_struct_free_f SessionMissionID_free;
asn_struct_print_f SessionMissionID_print;
asn_constr_check_f SessionMissionID_constraint;
ber_type_decoder_f SessionMissionID_decode_ber;
der_type_encoder_f SessionMissionID_encode_der;
xer_type_decoder_f SessionMissionID_decode_xer;
xer_type_encoder_f SessionMissionID_encode_xer;
jer_type_encoder_f SessionMissionID_encode_jer;
oer_type_decoder_f SessionMissionID_decode_oer;
oer_type_encoder_f SessionMissionID_encode_oer;
per_type_decoder_f SessionMissionID_decode_uper;
per_type_encoder_f SessionMissionID_encode_uper;
per_type_decoder_f SessionMissionID_decode_aper;
per_type_encoder_f SessionMissionID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SessionMissionID_H_ */
#include <asn_internal.h>
