/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "preprocessed_temp/AVM-Commons.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_UInt32_H_
#define	_UInt32_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UInt32 */
typedef unsigned long	 UInt32_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UInt32_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UInt32;
extern const asn_INTEGER_specifics_t asn_SPC_UInt32_specs_1;
asn_struct_free_f UInt32_free;
asn_struct_print_f UInt32_print;
asn_constr_check_f UInt32_constraint;
ber_type_decoder_f UInt32_decode_ber;
der_type_encoder_f UInt32_encode_der;
xer_type_decoder_f UInt32_decode_xer;
xer_type_encoder_f UInt32_encode_xer;
jer_type_encoder_f UInt32_encode_jer;
oer_type_decoder_f UInt32_decode_oer;
oer_type_encoder_f UInt32_encode_oer;
per_type_decoder_f UInt32_decode_uper;
per_type_encoder_f UInt32_encode_uper;
per_type_decoder_f UInt32_decode_aper;
per_type_encoder_f UInt32_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UInt32_H_ */
#include <asn_internal.h>
