/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MVM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MVM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_VehCodeEnum_H_
#define	_VehCodeEnum_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehCodeEnum {
	VehCodeEnum_unspecified	= 0,
	VehCodeEnum_pathNotDriveable	= 1,
	VehCodeEnum_onboardVehicleFault	= 2,
	VehCodeEnum_communicationFault	= 3,
	VehCodeEnum_vehicleEgressFault	= 4
	/*
	 * Enumeration is extensible
	 */
} e_VehCodeEnum;

/* VehCodeEnum */
typedef long	 VehCodeEnum_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehCodeEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehCodeEnum;
extern const asn_INTEGER_specifics_t asn_SPC_VehCodeEnum_specs_1;
asn_struct_free_f VehCodeEnum_free;
asn_struct_print_f VehCodeEnum_print;
asn_constr_check_f VehCodeEnum_constraint;
ber_type_decoder_f VehCodeEnum_decode_ber;
der_type_encoder_f VehCodeEnum_encode_der;
xer_type_decoder_f VehCodeEnum_decode_xer;
xer_type_encoder_f VehCodeEnum_encode_xer;
jer_type_encoder_f VehCodeEnum_encode_jer;
oer_type_decoder_f VehCodeEnum_decode_oer;
oer_type_encoder_f VehCodeEnum_encode_oer;
per_type_decoder_f VehCodeEnum_decode_uper;
per_type_encoder_f VehCodeEnum_encode_uper;
per_type_decoder_f VehCodeEnum_decode_aper;
per_type_encoder_f VehCodeEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehCodeEnum_H_ */
#include <asn_internal.h>
