/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_VehicleHornRequestEnum_H_
#define	_VehicleHornRequestEnum_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleHornRequestEnum {
	VehicleHornRequestEnum_none	= 0,
	VehicleHornRequestEnum_singleHorn	= 1,
	VehicleHornRequestEnum_doubleHorn	= 2,
	VehicleHornRequestEnum_holdHorn	= 3
} e_VehicleHornRequestEnum;

/* VehicleHornRequestEnum */
typedef long	 VehicleHornRequestEnum_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehicleHornRequestEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehicleHornRequestEnum;
extern const asn_INTEGER_specifics_t asn_SPC_VehicleHornRequestEnum_specs_1;
asn_struct_free_f VehicleHornRequestEnum_free;
asn_struct_print_f VehicleHornRequestEnum_print;
asn_constr_check_f VehicleHornRequestEnum_constraint;
ber_type_decoder_f VehicleHornRequestEnum_decode_ber;
der_type_encoder_f VehicleHornRequestEnum_encode_der;
xer_type_decoder_f VehicleHornRequestEnum_decode_xer;
xer_type_encoder_f VehicleHornRequestEnum_encode_xer;
jer_type_encoder_f VehicleHornRequestEnum_encode_jer;
oer_type_decoder_f VehicleHornRequestEnum_decode_oer;
oer_type_encoder_f VehicleHornRequestEnum_encode_oer;
per_type_decoder_f VehicleHornRequestEnum_decode_uper;
per_type_encoder_f VehicleHornRequestEnum_encode_uper;
per_type_decoder_f VehicleHornRequestEnum_decode_aper;
per_type_encoder_f VehicleHornRequestEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleHornRequestEnum_H_ */
#include <asn_internal.h>
