/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_VidRequestCommandEnum_H_
#define	_VidRequestCommandEnum_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VidRequestCommandEnum {
	VidRequestCommandEnum_generateNewCode	= 0,
	VidRequestCommandEnum_generateNewCodeAndPrepareForFlashing	= 1,
	VidRequestCommandEnum_flashing	= 2,
	VidRequestCommandEnum_successful	= 3
} e_VidRequestCommandEnum;

/* VidRequestCommandEnum */
typedef long	 VidRequestCommandEnum_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VidRequestCommandEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VidRequestCommandEnum;
extern const asn_INTEGER_specifics_t asn_SPC_VidRequestCommandEnum_specs_1;
asn_struct_free_f VidRequestCommandEnum_free;
asn_struct_print_f VidRequestCommandEnum_print;
asn_constr_check_f VidRequestCommandEnum_constraint;
ber_type_decoder_f VidRequestCommandEnum_decode_ber;
der_type_encoder_f VidRequestCommandEnum_encode_der;
xer_type_decoder_f VidRequestCommandEnum_decode_xer;
xer_type_encoder_f VidRequestCommandEnum_encode_xer;
jer_type_encoder_f VidRequestCommandEnum_encode_jer;
oer_type_decoder_f VidRequestCommandEnum_decode_oer;
oer_type_encoder_f VidRequestCommandEnum_encode_oer;
per_type_decoder_f VidRequestCommandEnum_decode_uper;
per_type_encoder_f VidRequestCommandEnum_encode_uper;
per_type_decoder_f VidRequestCommandEnum_decode_aper;
per_type_encoder_f VidRequestCommandEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VidRequestCommandEnum_H_ */
#include <asn_internal.h>
