/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_VidRequest_H_
#define	_VidRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Blinking.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VidRequest_PR {
	VidRequest_PR_NOTHING,	/* No components present */
	VidRequest_PR_blinking
	/* Extensions may appear below */
	
} VidRequest_PR;

/* VidRequest */
typedef struct VidRequest {
	VidRequest_PR present;
	union {
		Blinking_t	 blinking;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	};
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VidRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VidRequest;
extern asn_CHOICE_specifics_t asn_SPC_VidRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_VidRequest_1[1];
extern asn_per_constraints_t asn_PER_type_VidRequest_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _VidRequest_H_ */
#include <asn_internal.h>
