/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "preprocessed_temp/AVM-Commons.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_VidVehicleStateEnum_H_
#define	_VidVehicleStateEnum_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VidVehicleStateEnum {
	VidVehicleStateEnum_undefined	= 0,
	VidVehicleStateEnum_ready	= 1,
	VidVehicleStateEnum_lightFlashingInProgress	= 2,
	VidVehicleStateEnum_lightFlashingCompleted	= 3,
	VidVehicleStateEnum_lightFlashingFailed	= 4,
	VidVehicleStateEnum_authorized	= 5
} e_VidVehicleStateEnum;

/* VidVehicleStateEnum */
typedef long	 VidVehicleStateEnum_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VidVehicleStateEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VidVehicleStateEnum;
extern const asn_INTEGER_specifics_t asn_SPC_VidVehicleStateEnum_specs_1;
asn_struct_free_f VidVehicleStateEnum_free;
asn_struct_print_f VidVehicleStateEnum_print;
asn_constr_check_f VidVehicleStateEnum_constraint;
ber_type_decoder_f VidVehicleStateEnum_decode_ber;
der_type_encoder_f VidVehicleStateEnum_encode_der;
xer_type_decoder_f VidVehicleStateEnum_decode_xer;
xer_type_encoder_f VidVehicleStateEnum_encode_xer;
jer_type_encoder_f VidVehicleStateEnum_encode_jer;
oer_type_decoder_f VidVehicleStateEnum_decode_oer;
oer_type_encoder_f VidVehicleStateEnum_encode_oer;
per_type_decoder_f VidVehicleStateEnum_decode_uper;
per_type_encoder_f VidVehicleStateEnum_encode_uper;
per_type_decoder_f VidVehicleStateEnum_decode_aper;
per_type_encoder_f VidVehicleStateEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VidVehicleStateEnum_H_ */
#include <asn_internal.h>
