/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/AVM_TS_103_882/Gen_File`
 */

#ifndef	_WayPoint_H_
#define	_WayPoint_H_


#include <asn_application.h>

/* Including external dependencies */
#include "WaypointIndex.h"
#include "Pose.h"
#include "VelocityComponentValue.h"
#include "HighResCurvature.h"
#include "CartesianAngleValue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* WayPoint */
typedef struct WayPoint {
	WaypointIndex_t	*index;	/* OPTIONAL */
	Pose_t	 wayPointPose;
	VelocityComponentValue_t	 velocity;
	HighResCurvature_t	 curvature;
	CartesianAngleValue_t	*pitchAngle;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WayPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WayPoint;
extern asn_SEQUENCE_specifics_t asn_SPC_WayPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_WayPoint_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _WayPoint_H_ */
#include <asn_internal.h>
