/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#include "AlphabetIndicator.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_AlphabetIndicator_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_AlphabetIndicator_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  0,  32 }	/* (0..32) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_AlphabetIndicator_value2enum_1[] = {
	{ 1,	16,	"latinAlphabetNo1" },
	{ 2,	16,	"latinAlphabetNo2" },
	{ 3,	16,	"latinAlphabetNo3" },
	{ 4,	16,	"latinAlphabetNo4" },
	{ 5,	21,	"latinCyrillicAlphabet" },
	{ 6,	19,	"latinArabicAlphabet" },
	{ 7,	18,	"latinGreekAlphabet" },
	{ 8,	19,	"latinHebrewAlphabet" },
	{ 9,	16,	"latinAlphabetNo5" },
	{ 10,	16,	"latinAlphabetNo6" },
	{ 11,	11,	"twoOctetBMP" },
	{ 12,	18,	"forOctetCannonical" },
	{ 13,	16,	"latinAlphabetNo7" },
	{ 14,	16,	"latinAlphabetNo8" },
	{ 15,	16,	"latinAlphabetNo9" },
	{ 16,	17,	"latinAlphabetNo10" },
	{ 17,	17,	"latinThaiAlphabet" },
	{ 18,	4,	"utf8" },
	{ 19,	14,	"utf16BigEndian" },
	{ 20,	17,	"utf16LittleEndian" },
	{ 21,	14,	"utf32BigEndian" },
	{ 22,	17,	"utf32LittleEndian" },
	{ 23,	4,	"ucs4" },
	{ 24,	5,	"ascii" },
	{ 25,	5,	"iscii" },
	{ 26,	6,	"tis620" },
	{ 27,	5,	"vscii" },
	{ 28,	5,	"koi8R" },
	{ 29,	5,	"koi8U" },
	{ 30,	8,	"jisX0213" },
	{ 31,	7,	"gbt2312" },
	{ 32,	4,	"big5" },
	{ 33,	7,	"ksx1001" }
};
static const unsigned int asn_MAP_AlphabetIndicator_enum2value_1[] = {
	23,	/* ascii(24) */
	31,	/* big5(32) */
	11,	/* forOctetCannonical(12) */
	30,	/* gbt2312(31) */
	24,	/* iscii(25) */
	29,	/* jisX0213(30) */
	27,	/* koi8R(28) */
	28,	/* koi8U(29) */
	32,	/* ksx1001(33) */
	0,	/* latinAlphabetNo1(1) */
	15,	/* latinAlphabetNo10(16) */
	1,	/* latinAlphabetNo2(2) */
	2,	/* latinAlphabetNo3(3) */
	3,	/* latinAlphabetNo4(4) */
	8,	/* latinAlphabetNo5(9) */
	9,	/* latinAlphabetNo6(10) */
	12,	/* latinAlphabetNo7(13) */
	13,	/* latinAlphabetNo8(14) */
	14,	/* latinAlphabetNo9(15) */
	5,	/* latinArabicAlphabet(6) */
	4,	/* latinCyrillicAlphabet(5) */
	6,	/* latinGreekAlphabet(7) */
	7,	/* latinHebrewAlphabet(8) */
	16,	/* latinThaiAlphabet(17) */
	25,	/* tis620(26) */
	10,	/* twoOctetBMP(11) */
	22,	/* ucs4(23) */
	18,	/* utf16BigEndian(19) */
	19,	/* utf16LittleEndian(20) */
	20,	/* utf32BigEndian(21) */
	21,	/* utf32LittleEndian(22) */
	17,	/* utf8(18) */
	26	/* vscii(27) */
};
const asn_INTEGER_specifics_t asn_SPC_AlphabetIndicator_specs_1 = {
	asn_MAP_AlphabetIndicator_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_AlphabetIndicator_enum2value_1,	/* N => "tag"; sorted by N */
	33,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_AlphabetIndicator_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_AlphabetIndicator = {
	"AlphabetIndicator",
	"AlphabetIndicator",
	&asn_OP_NativeEnumerated,
	asn_DEF_AlphabetIndicator_tags_1,
	sizeof(asn_DEF_AlphabetIndicator_tags_1)
		/sizeof(asn_DEF_AlphabetIndicator_tags_1[0]), /* 1 */
	asn_DEF_AlphabetIndicator_tags_1,	/* Same as above */
	sizeof(asn_DEF_AlphabetIndicator_tags_1)
		/sizeof(asn_DEF_AlphabetIndicator_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_AlphabetIndicator_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_AlphabetIndicator_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_AlphabetIndicator_specs_1	/* Additional specs */
};

