/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_Co2EmissionValue_H_
#define	_Co2EmissionValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Int2Unsigned.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Co2EmissionValue */
typedef Int2Unsigned_t	 Co2EmissionValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Co2EmissionValue;
asn_struct_free_f Co2EmissionValue_free;
asn_struct_print_f Co2EmissionValue_print;
asn_constr_check_f Co2EmissionValue_constraint;
ber_type_decoder_f Co2EmissionValue_decode_ber;
der_type_encoder_f Co2EmissionValue_encode_der;
xer_type_decoder_f Co2EmissionValue_decode_xer;
xer_type_encoder_f Co2EmissionValue_encode_xer;
jer_type_encoder_f Co2EmissionValue_encode_jer;
oer_type_decoder_f Co2EmissionValue_decode_oer;
oer_type_encoder_f Co2EmissionValue_encode_oer;
per_type_decoder_f Co2EmissionValue_decode_uper;
per_type_encoder_f Co2EmissionValue_encode_uper;
per_type_decoder_f Co2EmissionValue_decode_aper;
per_type_encoder_f Co2EmissionValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Co2EmissionValue_H_ */
#include <asn_internal.h>
