/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_DriverClass_H_
#define	_DriverClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DriverClass {
	DriverClass_genericPerson	= 0,
	DriverClass_reducedMobility	= 1,
	DriverClass_otherDisability	= 2,
	DriverClass_officialAuthority	= 3,
	DriverClass_notToBeDisclosed	= 4,
	DriverClass_craftsPerson	= 5
} e_DriverClass;

/* DriverClass */
typedef long	 DriverClass_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DriverClass_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DriverClass;
asn_struct_free_f DriverClass_free;
asn_struct_print_f DriverClass_print;
asn_constr_check_f DriverClass_constraint;
ber_type_decoder_f DriverClass_decode_ber;
der_type_encoder_f DriverClass_encode_der;
xer_type_decoder_f DriverClass_decode_xer;
xer_type_encoder_f DriverClass_encode_xer;
jer_type_encoder_f DriverClass_encode_jer;
oer_type_decoder_f DriverClass_decode_oer;
oer_type_encoder_f DriverClass_encode_oer;
per_type_decoder_f DriverClass_decode_uper;
per_type_encoder_f DriverClass_encode_uper;
per_type_decoder_f DriverClass_decode_aper;
per_type_encoder_f DriverClass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _DriverClass_H_ */
#include <asn_internal.h>
