/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_Duration_H_
#define	_Duration_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Int4Unsigned.h"
#include "TimeUnit.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Duration */
typedef struct Duration {
	Int4Unsigned_t	 durationValue;
	TimeUnit_t	 timeUnit;	/* DEFAULT 0 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Duration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Duration;

#ifdef __cplusplus
}
#endif

#endif	/* _Duration_H_ */
#include <asn_internal.h>
