/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "preprocessed_temp/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_ETSI_ITS_CDD_IssuerIdentifier_H_
#define	_ETSI_ITS_CDD_IssuerIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ETSI-ITS-CDD_IssuerIdentifier */
typedef long	 ETSI_ITS_CDD_IssuerIdentifier_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ETSI_ITS_CDD_IssuerIdentifier_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_IssuerIdentifier;
asn_struct_free_f ETSI_ITS_CDD_IssuerIdentifier_free;
asn_struct_print_f ETSI_ITS_CDD_IssuerIdentifier_print;
asn_constr_check_f ETSI_ITS_CDD_IssuerIdentifier_constraint;
ber_type_decoder_f ETSI_ITS_CDD_IssuerIdentifier_decode_ber;
der_type_encoder_f ETSI_ITS_CDD_IssuerIdentifier_encode_der;
xer_type_decoder_f ETSI_ITS_CDD_IssuerIdentifier_decode_xer;
xer_type_encoder_f ETSI_ITS_CDD_IssuerIdentifier_encode_xer;
jer_type_encoder_f ETSI_ITS_CDD_IssuerIdentifier_encode_jer;
oer_type_decoder_f ETSI_ITS_CDD_IssuerIdentifier_decode_oer;
oer_type_encoder_f ETSI_ITS_CDD_IssuerIdentifier_encode_oer;
per_type_decoder_f ETSI_ITS_CDD_IssuerIdentifier_decode_uper;
per_type_encoder_f ETSI_ITS_CDD_IssuerIdentifier_encode_uper;
per_type_decoder_f ETSI_ITS_CDD_IssuerIdentifier_decode_aper;
per_type_encoder_f ETSI_ITS_CDD_IssuerIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_IssuerIdentifier_H_ */
#include <asn_internal.h>
