/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "preprocessed_temp/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_ETSI_ITS_CDD_GeoPosition_H_
#define	_ETSI_ITS_CDD_GeoPosition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ETSI-ITS-CDD_Latitude.h"
#include "ETSI-ITS-CDD_Longitude.h"
#include "AltitudeValue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ETSI-ITS-CDD_GeoPosition */
typedef struct ETSI_ITS_CDD_GeoPosition {
	ETSI_ITS_CDD_Latitude_t	 latitude;
	ETSI_ITS_CDD_Longitude_t	 longitude;
	AltitudeValue_t	*altitude;	/* DEFAULT 800001 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ETSI_ITS_CDD_GeoPosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_GeoPosition;
extern asn_SEQUENCE_specifics_t asn_SPC_ETSI_ITS_CDD_GeoPosition_specs_1;
extern asn_TYPE_member_t asn_MBR_ETSI_ITS_CDD_GeoPosition_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_GeoPosition_H_ */
#include <asn_internal.h>
