/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_EuroValueSubClass_H_
#define	_EuroValueSubClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EuroValueSubClass {
	EuroValueSubClass_noEntry	= 0,
	EuroValueSubClass_euro7G	= 1,
	EuroValueSubClass_euro7ext	= 2,
	EuroValueSubClass_euro7Gext	= 3
} e_EuroValueSubClass;

/* EuroValueSubClass */
typedef long	 EuroValueSubClass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EuroValueSubClass;
asn_struct_free_f EuroValueSubClass_free;
asn_struct_print_f EuroValueSubClass_print;
asn_constr_check_f EuroValueSubClass_constraint;
ber_type_decoder_f EuroValueSubClass_decode_ber;
der_type_encoder_f EuroValueSubClass_encode_der;
xer_type_decoder_f EuroValueSubClass_decode_xer;
xer_type_encoder_f EuroValueSubClass_encode_xer;
jer_type_encoder_f EuroValueSubClass_encode_jer;
oer_type_decoder_f EuroValueSubClass_decode_oer;
oer_type_encoder_f EuroValueSubClass_encode_oer;
per_type_decoder_f EuroValueSubClass_decode_uper;
per_type_encoder_f EuroValueSubClass_encode_uper;
per_type_decoder_f EuroValueSubClass_decode_aper;
per_type_encoder_f EuroValueSubClass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EuroValueSubClass_H_ */
#include <asn_internal.h>
