/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_InitialVehicleRegistrationDate_H_
#define	_InitialVehicleRegistrationDate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DateCompact.h"

#ifdef __cplusplus
extern "C" {
#endif

/* InitialVehicleRegistrationDate */
typedef DateCompact_t	 InitialVehicleRegistrationDate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitialVehicleRegistrationDate;
asn_struct_free_f InitialVehicleRegistrationDate_free;
asn_struct_print_f InitialVehicleRegistrationDate_print;
asn_constr_check_f InitialVehicleRegistrationDate_constraint;
ber_type_decoder_f InitialVehicleRegistrationDate_decode_ber;
der_type_encoder_f InitialVehicleRegistrationDate_encode_der;
xer_type_decoder_f InitialVehicleRegistrationDate_decode_xer;
xer_type_encoder_f InitialVehicleRegistrationDate_encode_xer;
jer_type_encoder_f InitialVehicleRegistrationDate_encode_jer;
oer_type_decoder_f InitialVehicleRegistrationDate_decode_oer;
oer_type_encoder_f InitialVehicleRegistrationDate_encode_oer;
per_type_decoder_f InitialVehicleRegistrationDate_decode_uper;
per_type_encoder_f InitialVehicleRegistrationDate_encode_uper;
per_type_decoder_f InitialVehicleRegistrationDate_decode_aper;
per_type_encoder_f InitialVehicleRegistrationDate_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _InitialVehicleRegistrationDate_H_ */
#include <asn_internal.h>
