/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-ParkingAvailability"
 * 	found in "preprocessed_temp/POIM-ParkingAvailability.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_LoadType_H_
#define	_LoadType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GoodsType.h"
#include "DangerousGoodsBasic.h"
#include "SpecialTransportType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LoadType */
typedef struct LoadType {
	GoodsType_t	*goodsType;	/* OPTIONAL */
	DangerousGoodsBasic_t	*dangerousGoodsType;	/* OPTIONAL */
	SpecialTransportType_t	 specialTransportType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoadType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadType;
extern asn_SEQUENCE_specifics_t asn_SPC_LoadType_specs_1;
extern asn_TYPE_member_t asn_MBR_LoadType_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LoadType_H_ */
#include <asn_internal.h>
