/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_Lpn_H_
#define	_Lpn_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EfcDataDictionary_CountryCode.h"
#include "AlphabetIndicator.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Lpn */
typedef struct Lpn {
	EfcDataDictionary_CountryCode_t	 countryCode;
	AlphabetIndicator_t	 alphabetIndicator;
	OCTET_STRING_t	 licencePlateNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Lpn_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Lpn;
extern asn_SEQUENCE_specifics_t asn_SPC_Lpn_specs_1;
extern asn_TYPE_member_t asn_MBR_Lpn_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Lpn_H_ */
#include <asn_internal.h>
