/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-ParkingAvailability"
 * 	found in "preprocessed_temp/POIM-ParkingAvailability.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_OccupancyTrend_H_
#define	_OccupancyTrend_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OccupancyTrend {
	OccupancyTrend_decreasing	= 0,
	OccupancyTrend_decreasingQuickly	= 1,
	OccupancyTrend_decreasingSlowly	= 2,
	OccupancyTrend_increasing	= 3,
	OccupancyTrend_increasingQuickly	= 4,
	OccupancyTrend_increasingSlowly	= 5,
	OccupancyTrend_stable	= 6,
	OccupancyTrend_variable	= 7,
	OccupancyTrend_unknown	= 15
} e_OccupancyTrend;

/* OccupancyTrend */
typedef long	 OccupancyTrend_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_OccupancyTrend_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_OccupancyTrend;
asn_struct_free_f OccupancyTrend_free;
asn_struct_print_f OccupancyTrend_print;
asn_constr_check_f OccupancyTrend_constraint;
ber_type_decoder_f OccupancyTrend_decode_ber;
der_type_encoder_f OccupancyTrend_encode_der;
xer_type_decoder_f OccupancyTrend_decode_xer;
xer_type_encoder_f OccupancyTrend_encode_xer;
jer_type_encoder_f OccupancyTrend_encode_jer;
oer_type_decoder_f OccupancyTrend_decode_oer;
oer_type_encoder_f OccupancyTrend_encode_oer;
per_type_decoder_f OccupancyTrend_decode_uper;
per_type_encoder_f OccupancyTrend_encode_uper;
per_type_decoder_f OccupancyTrend_decode_aper;
per_type_encoder_f OccupancyTrend_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _OccupancyTrend_H_ */
#include <asn_internal.h>
