/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-ParkingAvailability"
 * 	found in "preprocessed_temp/POIM-ParkingAvailability.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_ParkingSupplyCapabilitiesContainer_H_
#define	_ParkingSupplyCapabilitiesContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ParkingAreas;

/* ParkingSupplyCapabilitiesContainer */
typedef struct ParkingSupplyCapabilitiesContainer {
	A_SEQUENCE_OF(struct ParkingAreas) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParkingSupplyCapabilitiesContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParkingSupplyCapabilitiesContainer;
extern asn_SET_OF_specifics_t asn_SPC_ParkingSupplyCapabilitiesContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ParkingSupplyCapabilitiesContainer_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ParkingAreas.h"

#endif	/* _ParkingSupplyCapabilitiesContainer_H_ */
#include <asn_internal.h>
