/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-ParkingAvailability"
 * 	found in "preprocessed_temp/POIM-ParkingAvailability.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_ParkingFeeType_H_
#define	_ParkingFeeType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParkingFeeType {
	ParkingFeeType_timeDependentFee	= 0,
	ParkingFeeType_flatFee	= 1,
	ParkingFeeType_subscription	= 2
} e_ParkingFeeType;

/* ParkingFeeType */
typedef long	 ParkingFeeType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ParkingFeeType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ParkingFeeType;
asn_struct_free_f ParkingFeeType_free;
asn_struct_print_f ParkingFeeType_print;
asn_constr_check_f ParkingFeeType_constraint;
ber_type_decoder_f ParkingFeeType_decode_ber;
der_type_encoder_f ParkingFeeType_encode_der;
xer_type_decoder_f ParkingFeeType_decode_xer;
xer_type_encoder_f ParkingFeeType_encode_xer;
jer_type_encoder_f ParkingFeeType_encode_jer;
oer_type_decoder_f ParkingFeeType_decode_oer;
oer_type_encoder_f ParkingFeeType_encode_oer;
per_type_decoder_f ParkingFeeType_decode_uper;
per_type_encoder_f ParkingFeeType_encode_uper;
per_type_decoder_f ParkingFeeType_decode_aper;
per_type_encoder_f ParkingFeeType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ParkingFeeType_H_ */
#include <asn_internal.h>
