/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-ParkingAvailability"
 * 	found in "preprocessed_temp/POIM-ParkingAvailability.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_ParkingStatusContainer_H_
#define	_ParkingStatusContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OpeningStatus.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OccupancyInformation;
struct ParkingStatusList;

/* ParkingStatusContainer */
typedef struct ParkingStatusContainer {
	OpeningStatus_t	 currentFacilityStatus;
	struct OccupancyInformation	*currentOccupancy;	/* OPTIONAL */
	struct ParkingStatusList	*detailedStatus;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParkingStatusContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParkingStatusContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_ParkingStatusContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ParkingStatusContainer_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OccupancyInformation.h"
#include "ParkingStatusList.h"

#endif	/* _ParkingStatusContainer_H_ */
#include <asn_internal.h>
