/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-ParkingAvailability"
 * 	found in "preprocessed_temp/POIM-ParkingAvailability.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_ParkingStatus_H_
#define	_ParkingStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OccupancyInformation.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "ParkingReservationType.h"
#include "ParkingFeeType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EuVehicleCategoryCode;
struct LoadType;
struct ParkingOccupancyInfo;

/* ParkingStatus */
typedef struct ParkingStatus {
	struct ParkingStatus__vehicleTypes {
		A_SEQUENCE_OF(struct EuVehicleCategoryCode) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *vehicleTypes;
	struct ParkingStatus__reservationTypes {
		A_SEQUENCE_OF(ParkingReservationType_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *reservationTypes;
	struct ParkingStatus__loadTypes {
		A_SEQUENCE_OF(struct LoadType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *loadTypes;
	struct ParkingStatus__parkingFeeTypes {
		A_SEQUENCE_OF(ParkingFeeType_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *parkingFeeTypes;
	struct ParkingStatus__occupancyTypes {
		A_SEQUENCE_OF(struct ParkingOccupancyInfo) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *occupancyTypes;
	OccupancyInformation_t	 currentOccupancy;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParkingStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParkingStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_ParkingStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_ParkingStatus_1[6];
extern asn_per_constraints_t asn_PER_type_ParkingStatus_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EuVehicleCategoryCode.h"
#include "LoadType.h"
#include "ParkingOccupancyInfo.h"

#endif	/* _ParkingStatus_H_ */
#include <asn_internal.h>
