/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-ParkingAvailability"
 * 	found in "preprocessed_temp/POIM-ParkingAvailability.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_Periods_H_
#define	_Periods_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Period;

/* Periods */
typedef struct Periods {
	A_SEQUENCE_OF(struct Period) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Periods_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Periods;
extern asn_SET_OF_specifics_t asn_SPC_Periods_specs_1;
extern asn_TYPE_member_t asn_MBR_Periods_1[1];
extern asn_per_constraints_t asn_PER_type_Periods_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "POIM-ParkingAvailability_Period.h"

#endif	/* _Periods_H_ */
#include <asn_internal.h>
