/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-CommonContainers"
 * 	found in "preprocessed_temp/POIM-CommonContainers.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_PoiBlockManagementContainer_H_
#define	_PoiBlockManagementContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ETSI-ITS-CDD_Provider.h"
#include "Identifier2B.h"
#include "TimestampIts.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IvimReferences;
struct MapReferences;

/* PoiBlockManagementContainer */
typedef struct PoiBlockManagementContainer {
	ETSI_ITS_CDD_Provider_t	 serviceProviderId;
	Identifier2B_t	 blockIdentificationNumber;
	TimestampIts_t	 timestamp;
	struct IvimReferences	*linkedIvims;	/* OPTIONAL */
	struct MapReferences	*linkedMapems;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PoiBlockManagementContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PoiBlockManagementContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_PoiBlockManagementContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_PoiBlockManagementContainer_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IvimReferences.h"
#include "MapReferences.h"

#endif	/* _PoiBlockManagementContainer_H_ */
#include <asn_internal.h>
