/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-PDU-Description"
 * 	found in "preprocessed_temp/POIM-PDU-Description.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_POIM_H_
#define	_POIM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ItsPduHeader.h"
#include "WrappedPoiInformationBlocks.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* POIM */
typedef struct POIM {
	ItsPduHeader_t	 header;
	WrappedPoiInformationBlocks_t	 payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} POIM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_POIM;

#ifdef __cplusplus
}
#endif

#endif	/* _POIM_H_ */
#include <asn_internal.h>
