/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_ReceiptContract_H_
#define	_ReceiptContract_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EfcDataDictionary_Provider.h"
#include <OCTET_STRING.h>
#include "Int4Unsigned.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReceiptContract */
typedef struct ReceiptContract {
	EfcDataDictionary_Provider_t	 sessionContractProvider;
	OCTET_STRING_t	 sessionTypeOfContract;
	Int4Unsigned_t	 sessionContractSerialNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReceiptContract_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReceiptContract;

#ifdef __cplusplus
}
#endif

#endif	/* _ReceiptContract_H_ */
#include <asn_internal.h>
