/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "preprocessed_temp/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_ReferencePosition_H_
#define	_ReferencePosition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ETSI-ITS-CDD_Latitude.h"
#include "ETSI-ITS-CDD_Longitude.h"
#include "PosConfidenceEllipse.h"
#include "ETSI-ITS-CDD_Altitude.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReferencePosition */
typedef struct ReferencePosition {
	ETSI_ITS_CDD_Latitude_t	 latitude;
	ETSI_ITS_CDD_Longitude_t	 longitude;
	PosConfidenceEllipse_t	 positionConfidenceEllipse;
	ETSI_ITS_CDD_Altitude_t	 altitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReferencePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReferencePosition;
extern asn_SEQUENCE_specifics_t asn_SPC_ReferencePosition_specs_1;
extern asn_TYPE_member_t asn_MBR_ReferencePosition_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ReferencePosition_H_ */
#include <asn_internal.h>
