/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-CommonContainers"
 * 	found in "preprocessed_temp/POIM-CommonContainers.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_RelatedPoiInfoBlockContainer_H_
#define	_RelatedPoiInfoBlockContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RelatedPoiInfoBlock;

/* RelatedPoiInfoBlockContainer */
typedef struct RelatedPoiInfoBlockContainer {
	A_SEQUENCE_OF(struct RelatedPoiInfoBlock) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RelatedPoiInfoBlockContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RelatedPoiInfoBlockContainer;
extern asn_SET_OF_specifics_t asn_SPC_RelatedPoiInfoBlockContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_RelatedPoiInfoBlockContainer_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RelatedPoiInfoBlock.h"

#endif	/* _RelatedPoiInfoBlockContainer_H_ */
#include <asn_internal.h>
