/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_RelativePosition3d_H_
#define	_RelativePosition3d_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Int2Signed.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RelativePosition3d */
typedef struct RelativePosition3d {
	Int2Signed_t	 longitude;
	Int2Signed_t	 latitude;
	Int2Signed_t	*altitude;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RelativePosition3d_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RelativePosition3d;

#ifdef __cplusplus
}
#endif

#endif	/* _RelativePosition3d_H_ */
#include <asn_internal.h>
