/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_TrailerDetails_H_
#define	_TrailerDetails_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TrailerType.h"
#include "Axles.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TrailerDetails */
typedef struct TrailerDetails {
	TrailerType_t	 trailerType;
	Axles_t	 trailerAxles;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrailerDetails_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrailerDetails;
extern asn_SEQUENCE_specifics_t asn_SPC_TrailerDetails_specs_1;
extern asn_TYPE_member_t asn_MBR_TrailerDetails_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TrailerDetails_H_ */
#include <asn_internal.h>
