/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_TripPurpose_H_
#define	_TripPurpose_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TripPurpose {
	TripPurpose_genericTrip	= 0,
	TripPurpose_businessTrip	= 1,
	TripPurpose_privateTrip	= 2,
	TripPurpose_humanitarianAid	= 3,
	TripPurpose_militaryPurposes	= 4,
	TripPurpose_notToBeDisclosed	= 5,
	TripPurpose_craftBasedTrip	= 6,
	TripPurpose_combinedTransport	= 7
} e_TripPurpose;

/* TripPurpose */
typedef long	 TripPurpose_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TripPurpose_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TripPurpose;
asn_struct_free_f TripPurpose_free;
asn_struct_print_f TripPurpose_print;
asn_constr_check_f TripPurpose_constraint;
ber_type_decoder_f TripPurpose_decode_ber;
der_type_encoder_f TripPurpose_encode_der;
xer_type_decoder_f TripPurpose_decode_xer;
xer_type_encoder_f TripPurpose_encode_xer;
jer_type_encoder_f TripPurpose_encode_jer;
oer_type_decoder_f TripPurpose_decode_oer;
oer_type_encoder_f TripPurpose_encode_oer;
per_type_decoder_f TripPurpose_decode_uper;
per_type_encoder_f TripPurpose_encode_uper;
per_type_decoder_f TripPurpose_decode_aper;
per_type_encoder_f TripPurpose_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TripPurpose_H_ */
#include <asn_internal.h>
