/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_TyreConfiguration_H_
#define	_TyreConfiguration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TyreConfiguration {
	TyreConfiguration_notSpecified	= 0,
	TyreConfiguration_singleTyre	= 1,
	TyreConfiguration_dualTyres	= 2
} e_TyreConfiguration;

/* TyreConfiguration */
typedef long	 TyreConfiguration_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TyreConfiguration_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TyreConfiguration;
asn_struct_free_f TyreConfiguration_free;
asn_struct_print_f TyreConfiguration_print;
asn_constr_check_f TyreConfiguration_constraint;
ber_type_decoder_f TyreConfiguration_decode_ber;
der_type_encoder_f TyreConfiguration_encode_der;
xer_type_decoder_f TyreConfiguration_decode_xer;
xer_type_encoder_f TyreConfiguration_encode_xer;
jer_type_encoder_f TyreConfiguration_encode_jer;
oer_type_decoder_f TyreConfiguration_decode_oer;
oer_type_encoder_f TyreConfiguration_encode_oer;
per_type_decoder_f TyreConfiguration_decode_uper;
per_type_encoder_f TyreConfiguration_encode_uper;
per_type_decoder_f TyreConfiguration_decode_aper;
per_type_encoder_f TyreConfiguration_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TyreConfiguration_H_ */
#include <asn_internal.h>
