/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_VehicleUsageCategoryType_H_
#define	_VehicleUsageCategoryType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleUsageCategoryType {
	VehicleUsageCategoryType_noEntry	= 0,
	VehicleUsageCategoryType_handicappedPeople	= 1,
	VehicleUsageCategoryType_military	= 2,
	VehicleUsageCategoryType_police	= 3,
	VehicleUsageCategoryType_roadMaintenance	= 4,
	VehicleUsageCategoryType_circusTruck	= 5,
	VehicleUsageCategoryType_mobileShopTruck	= 6,
	VehicleUsageCategoryType_truckCarryingMilk	= 7,
	VehicleUsageCategoryType_truckCarryingTimber	= 8,
	VehicleUsageCategoryType_publicTransport	= 9,
	VehicleUsageCategoryType_enforcementAgent	= 10,
	VehicleUsageCategoryType_ambulance	= 11,
	VehicleUsageCategoryType_fireBrigade	= 12,
	VehicleUsageCategoryType_officialAuthority	= 13,
	VehicleUsageCategoryType_agriculturalVehicle	= 14,
	VehicleUsageCategoryType_bus	= 15,
	VehicleUsageCategoryType_mobileHome	= 16,
	VehicleUsageCategoryType_mobileCrane	= 17,
	VehicleUsageCategoryType_exceptionalTransport	= 18,
	VehicleUsageCategoryType_emperor	= 19,
	VehicleUsageCategoryType_vocationalVehicle	= 20,
	VehicleUsageCategoryType_vehicleLiableToToll	= 21,
	VehicleUsageCategoryType_craftsTransport	= 22,
	VehicleUsageCategoryType_combinedTransport	= 23
} e_VehicleUsageCategoryType;

/* VehicleUsageCategoryType */
typedef long	 VehicleUsageCategoryType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehicleUsageCategoryType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehicleUsageCategoryType;
asn_struct_free_f VehicleUsageCategoryType_free;
asn_struct_print_f VehicleUsageCategoryType_print;
asn_constr_check_f VehicleUsageCategoryType_constraint;
ber_type_decoder_f VehicleUsageCategoryType_decode_ber;
der_type_encoder_f VehicleUsageCategoryType_encode_der;
xer_type_decoder_f VehicleUsageCategoryType_decode_xer;
xer_type_encoder_f VehicleUsageCategoryType_encode_xer;
jer_type_encoder_f VehicleUsageCategoryType_encode_jer;
oer_type_decoder_f VehicleUsageCategoryType_decode_oer;
oer_type_encoder_f VehicleUsageCategoryType_encode_oer;
per_type_decoder_f VehicleUsageCategoryType_decode_uper;
per_type_encoder_f VehicleUsageCategoryType_encode_uper;
per_type_decoder_f VehicleUsageCategoryType_decode_aper;
per_type_encoder_f VehicleUsageCategoryType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleUsageCategoryType_H_ */
#include <asn_internal.h>
