/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_VehicleWidthOverall_H_
#define	_VehicleWidthOverall_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Int1Unsigned.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleWidthOverall */
typedef Int1Unsigned_t	 VehicleWidthOverall_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehicleWidthOverall_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehicleWidthOverall;
asn_struct_free_f VehicleWidthOverall_free;
asn_struct_print_f VehicleWidthOverall_print;
asn_constr_check_f VehicleWidthOverall_constraint;
ber_type_decoder_f VehicleWidthOverall_decode_ber;
der_type_encoder_f VehicleWidthOverall_encode_der;
xer_type_decoder_f VehicleWidthOverall_decode_xer;
xer_type_encoder_f VehicleWidthOverall_encode_xer;
jer_type_encoder_f VehicleWidthOverall_encode_jer;
oer_type_decoder_f VehicleWidthOverall_decode_oer;
oer_type_encoder_f VehicleWidthOverall_encode_oer;
per_type_decoder_f VehicleWidthOverall_decode_uper;
per_type_encoder_f VehicleWidthOverall_encode_uper;
per_type_decoder_f VehicleWidthOverall_decode_aper;
per_type_encoder_f VehicleWidthOverall_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleWidthOverall_H_ */
#include <asn_internal.h>
