/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDataDictionary"
 * 	found in "preprocessed_temp/ISO 17573-3 EfcDataDictionary V1.6.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_VehicleWeightUnladen_H_
#define	_VehicleWeightUnladen_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Int2Unsigned.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleWeightUnladen */
typedef Int2Unsigned_t	 VehicleWeightUnladen_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehicleWeightUnladen_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehicleWeightUnladen;
asn_struct_free_f VehicleWeightUnladen_free;
asn_struct_print_f VehicleWeightUnladen_print;
asn_constr_check_f VehicleWeightUnladen_constraint;
ber_type_decoder_f VehicleWeightUnladen_decode_ber;
der_type_encoder_f VehicleWeightUnladen_encode_der;
xer_type_decoder_f VehicleWeightUnladen_decode_xer;
xer_type_encoder_f VehicleWeightUnladen_encode_xer;
jer_type_encoder_f VehicleWeightUnladen_encode_jer;
oer_type_decoder_f VehicleWeightUnladen_decode_oer;
oer_type_encoder_f VehicleWeightUnladen_encode_oer;
per_type_decoder_f VehicleWeightUnladen_decode_uper;
per_type_encoder_f VehicleWeightUnladen_encode_uper;
per_type_decoder_f VehicleWeightUnladen_decode_aper;
per_type_encoder_f VehicleWeightUnladen_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleWeightUnladen_H_ */
#include <asn_internal.h>
