/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "POIM-PDU-Description"
 * 	found in "preprocessed_temp/POIM-PDU-Description.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PA_TS_103_916/Gen_File`
 */

#ifndef	_WrappedPoiInformationBlocks_H_
#define	_WrappedPoiInformationBlocks_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct WrappedPoiInformationBlock;

/* WrappedPoiInformationBlocks */
typedef struct WrappedPoiInformationBlocks {
	A_SEQUENCE_OF(struct WrappedPoiInformationBlock) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WrappedPoiInformationBlocks_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WrappedPoiInformationBlocks;
extern asn_SET_OF_specifics_t asn_SPC_WrappedPoiInformationBlocks_specs_1;
extern asn_TYPE_member_t asn_MBR_WrappedPoiInformationBlocks_1[1];
extern asn_per_constraints_t asn_PER_type_WrappedPoiInformationBlocks_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "WrappedPoiInformationBlock.h"

#endif	/* _WrappedPoiInformationBlocks_H_ */
#include <asn_internal.h>
