/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "preprocessed_temp/VAM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/VAM_TS_103_300-3/Gen_File`
 */

#include "VruClusterInformationContainer.h"

static int
memb_vruClusterInformation_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	//PROVA WITH COMPONENTS 
	// Tipo con vincolo: vruClusterInformation
	// Accesso alla struttura tipizzata
	const vruClusterInformation_t *typed_struct = (const vruClusterInformation_t *)sptr;
	// Memorizzazione del tipo per uso successivo
	const char *constraint_type = "vruClusterInformation";
	// Verifica del componente: clusterId (optional: no)
	// Verifica del componente: clusterBoundingBoxShape (optional: no)
	/* Component clusterBoundingBoxShape is mandatory, presence is implicit */
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_vruClusterInformation_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_vruClusterInformation_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_VruClusterInformationContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VruClusterInformationContainer, vruClusterInformation),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VruClusterInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_vruClusterInformation_constr_2,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_vruClusterInformation_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_vruClusterInformation_constraint_1
		},
		0, 0, /* No default value */
		"vruClusterInformation"
		},
};
static const ber_tlv_tag_t asn_DEF_VruClusterInformationContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VruClusterInformationContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* vruClusterInformation */
};
asn_SEQUENCE_specifics_t asn_SPC_VruClusterInformationContainer_specs_1 = {
	sizeof(struct VruClusterInformationContainer),
	offsetof(struct VruClusterInformationContainer, _asn_ctx),
	asn_MAP_VruClusterInformationContainer_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_VruClusterInformationContainer = {
	"VruClusterInformationContainer",
	"VruClusterInformationContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_VruClusterInformationContainer_tags_1,
	sizeof(asn_DEF_VruClusterInformationContainer_tags_1)
		/sizeof(asn_DEF_VruClusterInformationContainer_tags_1[0]), /* 1 */
	asn_DEF_VruClusterInformationContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_VruClusterInformationContainer_tags_1)
		/sizeof(asn_DEF_VruClusterInformationContainer_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_VruClusterInformationContainer_1,
	1,	/* Elements count */
	&asn_SPC_VruClusterInformationContainer_specs_1	/* Additional specs */
};

