/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TIS-TPG-Transactions-Descriptions"
 * 	found in "preprocessed_temp/TIS-TPG-Transactions-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/TIS_TPG_TS_101_556-2/Gen_File`
 */

#ifndef	_TisTpgVDPM_H_
#define	_TisTpgVDPM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TisTpgVDPM-Management.h"
#include "PlacardTable.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VehicleSpecificData;

/* TisTpgVDPM */
typedef struct TisTpgVDPM {
	TisTpgVDPM_Management_t	 management;
	PlacardTable_t	 placardTable;
	struct VehicleSpecificData	*vehicleSpecificData;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TisTpgVDPM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TisTpgVDPM;
extern asn_SEQUENCE_specifics_t asn_SPC_TisTpgVDPM_specs_1;
extern asn_TYPE_member_t asn_MBR_TisTpgVDPM_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VehicleSpecificData.h"

#endif	/* _TisTpgVDPM_H_ */
#include <asn_internal.h>
