/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103097Module"
 * 	found in "preprocessed_temp/EtsiTs103097Module.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/PKI_TS_102_941/Gen_File`
 */

#ifndef	_EtsiTs103097Data_Unsecured_H_
#define	_EtsiTs103097Data_Unsecured_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _EtsiTs103097Data_Unsecured_H_ */
#include <asn_internal.h>
