/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "preprocessed_temp/Ieee1609Dot2.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IEEE_1609.2.1/Gen_File`
 */

#include "Aes128CcmCiphertext.h"

/*
 * This type is implemented using One28BitCcmCiphertext,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_Aes128CcmCiphertext_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Aes128CcmCiphertext = {
	"Aes128CcmCiphertext",
	"Aes128CcmCiphertext",
	&asn_OP_SEQUENCE,
	asn_DEF_Aes128CcmCiphertext_tags_1,
	sizeof(asn_DEF_Aes128CcmCiphertext_tags_1)
		/sizeof(asn_DEF_Aes128CcmCiphertext_tags_1[0]), /* 1 */
	asn_DEF_Aes128CcmCiphertext_tags_1,	/* Same as above */
	sizeof(asn_DEF_Aes128CcmCiphertext_tags_1)
		/sizeof(asn_DEF_Aes128CcmCiphertext_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_One28BitCcmCiphertext_1,
	2,	/* Elements count */
	&asn_SPC_One28BitCcmCiphertext_specs_1	/* Additional specs */
};

