/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "preprocessed_temp/Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IEEE_1609.2.1/Gen_File`
 */

#ifndef	_AliasRaAcaCertRequest_H_
#define	_AliasRaAcaCertRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ScmsPdu-Scoped.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AliasRaAcaCertRequest */
typedef ScmsPdu_Scoped_204P0_t	 AliasRaAcaCertRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AliasRaAcaCertRequest;
asn_struct_free_f AliasRaAcaCertRequest_free;
asn_struct_print_f AliasRaAcaCertRequest_print;
asn_constr_check_f AliasRaAcaCertRequest_constraint;
ber_type_decoder_f AliasRaAcaCertRequest_decode_ber;
der_type_encoder_f AliasRaAcaCertRequest_encode_der;
xer_type_decoder_f AliasRaAcaCertRequest_decode_xer;
xer_type_encoder_f AliasRaAcaCertRequest_encode_xer;
jer_type_encoder_f AliasRaAcaCertRequest_encode_jer;
oer_type_decoder_f AliasRaAcaCertRequest_decode_oer;
oer_type_encoder_f AliasRaAcaCertRequest_encode_oer;
per_type_decoder_f AliasRaAcaCertRequest_decode_uper;
per_type_encoder_f AliasRaAcaCertRequest_encode_uper;
per_type_decoder_f AliasRaAcaCertRequest_decode_aper;
per_type_encoder_f AliasRaAcaCertRequest_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AliasRaAcaCertRequest_H_ */
#include <asn_internal.h>
