/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1CamRaInterface"
 * 	found in "preprocessed_temp/Ieee1609Dot2Dot1CamRaInterface.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IEEE_1609.2.1/Gen_File`
 */

#ifndef	_CamRaInterfacePdu_H_
#define	_CamRaInterfacePdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RaCamBatchRequest.h"
#include "CamRaBatchResponse.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CamRaInterfacePdu_PR {
	CamRaInterfacePdu_PR_NOTHING,	/* No components present */
	CamRaInterfacePdu_PR_raCamBatchRequest,
	CamRaInterfacePdu_PR_camRaBatchResponse
	/* Extensions may appear below */
	
} CamRaInterfacePdu_PR;

/* CamRaInterfacePdu */
typedef struct CamRaInterfacePdu {
	CamRaInterfacePdu_PR present;
	union {
		RaCamBatchRequest_t	 raCamBatchRequest;
		CamRaBatchResponse_t	 camRaBatchResponse;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	};
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CamRaInterfacePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamRaInterfacePdu;

#ifdef __cplusplus
}
#endif

#endif	/* _CamRaInterfacePdu_H_ */
#include <asn_internal.h>
