/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "preprocessed_temp/Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IEEE_1609.2.1/Gen_File`
 */

#ifndef	_Extension_H_
#define	_Extension_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ExtId.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "HashedId8.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ieee1609HeaderInfoExtensions__content_PR {
	Ieee1609HeaderInfoExtensions__content_PR_NOTHING,	/* No components present */
	Ieee1609HeaderInfoExtensions__content_PR_HashedId8
} Ieee1609HeaderInfoExtensions__content_PR;

/* Extension */
typedef struct Ieee1609HeaderInfoExtensions {
	ExtId_t	 id;
	struct Ieee1609HeaderInfoExtensions__content {
		Ieee1609HeaderInfoExtensions__content_PR present;
		union {
			HashedId8_t	 HashedId8;
		};
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} content;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ieee1609HeaderInfoExtensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ieee1609HeaderInfoExtensions;
extern asn_SEQUENCE_specifics_t asn_SPC_Ieee1609HeaderInfoExtensions_specs_1;
extern asn_TYPE_member_t asn_MBR_Ieee1609HeaderInfoExtensions_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Extension_H_ */
#include <asn_internal.h>
