/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "preprocessed_temp/Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IEEE_1609.2.1/Gen_File`
 */

#ifndef	_Ieee1609Dot2Data_SignedX509AuthenticatedCertRequest_H_
#define	_Ieee1609Dot2Data_SignedX509AuthenticatedCertRequest_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _Ieee1609Dot2Data_SignedX509AuthenticatedCertRequest_H_ */
#include <asn_internal.h>
