/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Acpc"
 * 	found in "preprocessed_temp/Ieee1609Dot2Dot1Acpc.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IEEE_1609.2.1/Gen_File`
 */

#ifndef	_SignedAprvBinaryTree_H_
#define	_SignedAprvBinaryTree_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Ieee1609Dot2Data-Signed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SignedAprvBinaryTree */
typedef Ieee1609Dot2Data_Signed_228P1_t	 SignedAprvBinaryTree_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignedAprvBinaryTree;
asn_struct_free_f SignedAprvBinaryTree_free;
asn_struct_print_f SignedAprvBinaryTree_print;
asn_constr_check_f SignedAprvBinaryTree_constraint;
ber_type_decoder_f SignedAprvBinaryTree_decode_ber;
der_type_encoder_f SignedAprvBinaryTree_encode_der;
xer_type_decoder_f SignedAprvBinaryTree_decode_xer;
xer_type_encoder_f SignedAprvBinaryTree_encode_xer;
jer_type_encoder_f SignedAprvBinaryTree_encode_jer;
oer_type_decoder_f SignedAprvBinaryTree_decode_oer;
oer_type_encoder_f SignedAprvBinaryTree_encode_oer;
per_type_decoder_f SignedAprvBinaryTree_decode_uper;
per_type_encoder_f SignedAprvBinaryTree_encode_uper;
per_type_decoder_f SignedAprvBinaryTree_decode_aper;
per_type_encoder_f SignedAprvBinaryTree_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SignedAprvBinaryTree_H_ */
#include <asn_internal.h>
