/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MVM-PDU-Descriptions"
 * 	found in "modified_MVM-PDU-Descriptions.asn"
 */

#ifndef	_BasicVehicleClassEnum_H_
#define	_BasicVehicleClassEnum_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BasicVehicleClassEnum {
	BasicVehicleClassEnum_none	= 0,
	BasicVehicleClassEnum_unknown	= 1,
	BasicVehicleClassEnum_special	= 2,
	BasicVehicleClassEnum_moto	= 3,
	BasicVehicleClassEnum_car	= 4,
	BasicVehicleClassEnum_carOther	= 5,
	BasicVehicleClassEnum_bus	= 6,
	BasicVehicleClassEnum_axleCnt2	= 7,
	BasicVehicleClassEnum_axleCnt3	= 8,
	BasicVehicleClassEnum_axleCnt4	= 9,
	BasicVehicleClassEnum_axleCnt4Trailer	= 10,
	BasicVehicleClassEnum_axleCnt5Trailer	= 11,
	BasicVehicleClassEnum_axleCnt6Trailer	= 12,
	BasicVehicleClassEnum_axleCnt5MultiTrailer	= 13,
	BasicVehicleClassEnum_axleCnt6MultiTrailer	= 14,
	BasicVehicleClassEnum_axleCnt7MultiTrailer	= 15
	/*
	 * Enumeration is extensible
	 */
} e_BasicVehicleClassEnum;

/* BasicVehicleClassEnum */
typedef long	 BasicVehicleClassEnum_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_BasicVehicleClassEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BasicVehicleClassEnum;
extern const asn_INTEGER_specifics_t asn_SPC_BasicVehicleClassEnum_specs_1;
asn_struct_free_f BasicVehicleClassEnum_free;
asn_struct_print_f BasicVehicleClassEnum_print;
asn_constr_check_f BasicVehicleClassEnum_constraint;
ber_type_decoder_f BasicVehicleClassEnum_decode_ber;
der_type_encoder_f BasicVehicleClassEnum_encode_der;
xer_type_decoder_f BasicVehicleClassEnum_decode_xer;
xer_type_encoder_f BasicVehicleClassEnum_encode_xer;
jer_type_encoder_f BasicVehicleClassEnum_encode_jer;
oer_type_decoder_f BasicVehicleClassEnum_decode_oer;
oer_type_encoder_f BasicVehicleClassEnum_encode_oer;
per_type_decoder_f BasicVehicleClassEnum_decode_uper;
per_type_encoder_f BasicVehicleClassEnum_encode_uper;
per_type_decoder_f BasicVehicleClassEnum_decode_aper;
per_type_encoder_f BasicVehicleClassEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _BasicVehicleClassEnum_H_ */
#include <asn_internal.h>
