/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "modified_MIM-PDU-Descriptions.asn"
 */

#ifndef	_Blinking_H_
#define	_Blinking_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UInt64.h"
#include "UInt8.h"
#include "VidRequestCommandEnum.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Blinking */
typedef struct Blinking {
	UInt64_t	 vidRoPublicKey;
	UInt8_t	 codeLength;
	VidRequestCommandEnum_t	 blinkingCommand;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Blinking_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Blinking;
extern asn_SEQUENCE_specifics_t asn_SPC_Blinking_specs_1;
extern asn_TYPE_member_t asn_MBR_Blinking_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Blinking_H_ */
#include <asn_internal.h>
