/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "AVM-Commons.asn"
 */

#ifndef	_Centimetre_H_
#define	_Centimetre_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Centimetre {
	Centimetre_negativeOutOfRange	= -524287,
	Centimetre_positiveOutOfRange	= 524287,
	Centimetre_unavailable	= -524288
} e_Centimetre;

/* Centimetre */
typedef long	 Centimetre_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Centimetre_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Centimetre;
asn_struct_free_f Centimetre_free;
asn_struct_print_f Centimetre_print;
asn_constr_check_f Centimetre_constraint;
ber_type_decoder_f Centimetre_decode_ber;
der_type_encoder_f Centimetre_encode_der;
xer_type_decoder_f Centimetre_decode_xer;
xer_type_encoder_f Centimetre_encode_xer;
jer_type_encoder_f Centimetre_encode_jer;
oer_type_decoder_f Centimetre_decode_oer;
oer_type_encoder_f Centimetre_encode_oer;
per_type_decoder_f Centimetre_decode_uper;
per_type_encoder_f Centimetre_encode_uper;
per_type_decoder_f Centimetre_decode_aper;
per_type_encoder_f Centimetre_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Centimetre_H_ */
#include <asn_internal.h>
