/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "modified_MIM-PDU-Descriptions.asn"
 */

#ifndef	_ControlParameter_H_
#define	_ControlParameter_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ControlAcceleration.h"
#include "ControlVelocity.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ControlParameter_PR {
	ControlParameter_PR_NOTHING,	/* No components present */
	ControlParameter_PR_controlAcceleration,
	ControlParameter_PR_controlVelocity
} ControlParameter_PR;

/* ControlParameter */
typedef struct ControlParameter {
	ControlParameter_PR present;
	union ControlParameter_u {
		ControlAcceleration_t	 controlAcceleration;
		ControlVelocity_t	 controlVelocity;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ControlParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ControlParameter;
extern asn_CHOICE_specifics_t asn_SPC_ControlParameter_specs_1;
extern asn_TYPE_member_t asn_MBR_ControlParameter_1[2];
extern asn_per_constraints_t asn_PER_type_ControlParameter_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ControlParameter_H_ */
#include <asn_internal.h>
