/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "modified_MIM-PDU-Descriptions.asn"
 */

#ifndef	_ControlVelocity_H_
#define	_ControlVelocity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VelocityComponentValue.h"
#include "Centimetre.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ControlVelocity */
typedef struct ControlVelocity {
	VelocityComponentValue_t	 velocity;
	Centimetre_t	*distanceToStop;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ControlVelocity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ControlVelocity;
extern asn_SEQUENCE_specifics_t asn_SPC_ControlVelocity_specs_1;
extern asn_TYPE_member_t asn_MBR_ControlVelocity_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ControlVelocity_H_ */
#include <asn_internal.h>
