/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "modified_MIM-PDU-Descriptions.asn"
 */

#ifndef	_InterlockEnum_H_
#define	_InterlockEnum_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InterlockEnum {
	InterlockEnum_none	= 0,
	InterlockEnum_zonalInterlock	= 1,
	InterlockEnum_globalStop	= 2
} e_InterlockEnum;

/* InterlockEnum */
typedef long	 InterlockEnum_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_InterlockEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_InterlockEnum;
extern const asn_INTEGER_specifics_t asn_SPC_InterlockEnum_specs_1;
asn_struct_free_f InterlockEnum_free;
asn_struct_print_f InterlockEnum_print;
asn_constr_check_f InterlockEnum_constraint;
ber_type_decoder_f InterlockEnum_decode_ber;
der_type_encoder_f InterlockEnum_encode_der;
xer_type_decoder_f InterlockEnum_decode_xer;
xer_type_encoder_f InterlockEnum_encode_xer;
jer_type_encoder_f InterlockEnum_encode_jer;
oer_type_decoder_f InterlockEnum_decode_oer;
oer_type_encoder_f InterlockEnum_encode_oer;
per_type_decoder_f InterlockEnum_decode_uper;
per_type_encoder_f InterlockEnum_encode_uper;
per_type_decoder_f InterlockEnum_decode_aper;
per_type_encoder_f InterlockEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _InterlockEnum_H_ */
#include <asn_internal.h>
