/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MVM-PDU-Descriptions"
 * 	found in "modified_MVM-PDU-Descriptions.asn"
 */

#ifndef	_ParkingBrakeStateEnum_H_
#define	_ParkingBrakeStateEnum_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParkingBrakeStateEnum {
	ParkingBrakeStateEnum_unknown	= 0,
	ParkingBrakeStateEnum_engaging	= 1,
	ParkingBrakeStateEnum_engaged	= 2,
	ParkingBrakeStateEnum_disengaging	= 3,
	ParkingBrakeStateEnum_disengaged	= 4
} e_ParkingBrakeStateEnum;

/* ParkingBrakeStateEnum */
typedef long	 ParkingBrakeStateEnum_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ParkingBrakeStateEnum_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ParkingBrakeStateEnum;
extern const asn_INTEGER_specifics_t asn_SPC_ParkingBrakeStateEnum_specs_1;
asn_struct_free_f ParkingBrakeStateEnum_free;
asn_struct_print_f ParkingBrakeStateEnum_print;
asn_constr_check_f ParkingBrakeStateEnum_constraint;
ber_type_decoder_f ParkingBrakeStateEnum_decode_ber;
der_type_encoder_f ParkingBrakeStateEnum_encode_der;
xer_type_decoder_f ParkingBrakeStateEnum_decode_xer;
xer_type_encoder_f ParkingBrakeStateEnum_encode_xer;
jer_type_encoder_f ParkingBrakeStateEnum_encode_jer;
oer_type_decoder_f ParkingBrakeStateEnum_decode_oer;
oer_type_encoder_f ParkingBrakeStateEnum_encode_oer;
per_type_decoder_f ParkingBrakeStateEnum_decode_uper;
per_type_encoder_f ParkingBrakeStateEnum_encode_uper;
per_type_decoder_f ParkingBrakeStateEnum_decode_aper;
per_type_encoder_f ParkingBrakeStateEnum_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ParkingBrakeStateEnum_H_ */
#include <asn_internal.h>
