/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "AVM-Commons.asn"
 */

#include "SafetyViolationsEnum.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_SafetyViolationsEnum_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_SafetyViolationsEnum_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  11 }	/* (0..11,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_SafetyViolationsEnum_value2enum_1[] = {
	{ 0,	11,	"noViolation" },
	{ 1,	27,	"noDrivingPermissionReceived" },
	{ 2,	27,	"lastDrivingPermissionTooOld" },
	{ 3,	28,	"crcViolationClockSyncRequest" },
	{ 4,	29,	"crcViolationDrivingPermission" },
	{ 5,	23,	"expirationTimeViolation" },
	{ 6,	24,	"drivingDirectionMismatch" },
	{ 7,	17,	"velocityViolation" },
	{ 8,	21,	"curvatureMinViolation" },
	{ 9,	21,	"curvatureMaxViolation" },
	{ 10,	21,	"expirationTimeTooHigh" },
	{ 11,	10,	"monitoring" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_SafetyViolationsEnum_enum2value_1[] = {
	3,	/* crcViolationClockSyncRequest(3) */
	4,	/* crcViolationDrivingPermission(4) */
	9,	/* curvatureMaxViolation(9) */
	8,	/* curvatureMinViolation(8) */
	6,	/* drivingDirectionMismatch(6) */
	10,	/* expirationTimeTooHigh(10) */
	5,	/* expirationTimeViolation(5) */
	2,	/* lastDrivingPermissionTooOld(2) */
	11,	/* monitoring(11) */
	1,	/* noDrivingPermissionReceived(1) */
	0,	/* noViolation(0) */
	7	/* velocityViolation(7) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_SafetyViolationsEnum_specs_1 = {
	asn_MAP_SafetyViolationsEnum_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_SafetyViolationsEnum_enum2value_1,	/* N => "tag"; sorted by N */
	12,	/* Number of elements in the maps */
	13,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_SafetyViolationsEnum_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_SafetyViolationsEnum = {
	"SafetyViolationsEnum",
	"SafetyViolationsEnum",
	&asn_OP_NativeEnumerated,
	asn_DEF_SafetyViolationsEnum_tags_1,
	sizeof(asn_DEF_SafetyViolationsEnum_tags_1)
		/sizeof(asn_DEF_SafetyViolationsEnum_tags_1[0]), /* 1 */
	asn_DEF_SafetyViolationsEnum_tags_1,	/* Same as above */
	sizeof(asn_DEF_SafetyViolationsEnum_tags_1)
		/sizeof(asn_DEF_SafetyViolationsEnum_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_SafetyViolationsEnum_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_SafetyViolationsEnum_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_SafetyViolationsEnum_specs_1	/* Additional specs */
};

