/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MIM-PDU-Descriptions"
 * 	found in "modified_MIM-PDU-Descriptions.asn"
 */

#ifndef	_StateTrajectory_H_
#define	_StateTrajectory_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct StatePoint;

/* StateTrajectory */
typedef struct StateTrajectory {
	A_SEQUENCE_OF(struct StatePoint) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StateTrajectory_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StateTrajectory;
extern asn_SET_OF_specifics_t asn_SPC_StateTrajectory_specs_1;
extern asn_TYPE_member_t asn_MBR_StateTrajectory_1[1];
extern asn_per_constraints_t asn_PER_type_StateTrajectory_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "StatePoint.h"

#endif	/* _StateTrajectory_H_ */
#include <asn_internal.h>
