/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "AVM-Commons.asn"
 */

#ifndef	_SystemManagementData_H_
#define	_SystemManagementData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SessionMissionID.h"
#include "VehicleID.h"
#include "FacilityID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SystemManagementData */
typedef struct SystemManagementData {
	SessionMissionID_t	*sessionID;	/* OPTIONAL */
	SessionMissionID_t	*missionID;	/* OPTIONAL */
	VehicleID_t	*vehicleID;	/* OPTIONAL */
	FacilityID_t	*facilityID;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SystemManagementData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SystemManagementData;
extern asn_SEQUENCE_specifics_t asn_SPC_SystemManagementData_specs_1;
extern asn_TYPE_member_t asn_MBR_SystemManagementData_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SystemManagementData_H_ */
#include <asn_internal.h>
