/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "AVM-Commons.asn"
 */

#ifndef	_UInt64_H_
#define	_UInt64_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UInt64 */
typedef INTEGER_t	 UInt64_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UInt64_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UInt64;
asn_struct_free_f UInt64_free;
asn_struct_print_f UInt64_print;
asn_constr_check_f UInt64_constraint;
ber_type_decoder_f UInt64_decode_ber;
der_type_encoder_f UInt64_encode_der;
xer_type_decoder_f UInt64_decode_xer;
xer_type_encoder_f UInt64_encode_xer;
jer_type_encoder_f UInt64_encode_jer;
oer_type_decoder_f UInt64_decode_oer;
oer_type_encoder_f UInt64_encode_oer;
per_type_decoder_f UInt64_decode_uper;
per_type_encoder_f UInt64_encode_uper;
per_type_decoder_f UInt64_decode_aper;
per_type_encoder_f UInt64_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UInt64_H_ */
#include <asn_internal.h>
