/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MVM-PDU-Descriptions"
 * 	found in "modified_MVM-PDU-Descriptions.asn"
 */

#ifndef	_VehicleProperties_H_
#define	_VehicleProperties_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BasicVehicleClassEnum.h"
#include "Centimetre.h"
#include "VehicleMass.h"
#include "VelocityComponentValue.h"
#include "HighResCurvature.h"
#include "RadPerSecond.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleProperties */
typedef struct VehicleProperties {
	BasicVehicleClassEnum_t	 basicVehicleClass;
	Centimetre_t	 vehicleLength;
	Centimetre_t	 vehicleWheelbase;
	Centimetre_t	 vehicleRearOverhang;
	Centimetre_t	 vehicleWidth;
	Centimetre_t	 vehicleTireWidth;
	Centimetre_t	 vehicleTrackWidth;
	VehicleMass_t	 vehicleMass;
	VelocityComponentValue_t	 vehicleSpeedLimit;
	HighResCurvature_t	 vehicleCuvatureLimit;
	RadPerSecond_t	 vehicleMaxAngularSteeringRate;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleProperties_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleProperties;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleProperties_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleProperties_1[11];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleProperties_H_ */
#include <asn_internal.h>
