/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVM-Commons"
 * 	found in "AVM-Commons.asn"
 */

#ifndef	_VehicleID_H_
#define	_VehicleID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleID */
typedef IA5String_t	 VehicleID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehicleID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehicleID;
asn_struct_free_f VehicleID_free;
asn_struct_print_f VehicleID_print;
asn_constr_check_f VehicleID_constraint;
ber_type_decoder_f VehicleID_decode_ber;
der_type_encoder_f VehicleID_encode_der;
xer_type_decoder_f VehicleID_decode_xer;
xer_type_encoder_f VehicleID_encode_xer;
jer_type_encoder_f VehicleID_encode_jer;
oer_type_decoder_f VehicleID_decode_oer;
oer_type_encoder_f VehicleID_encode_oer;
per_type_decoder_f VehicleID_decode_uper;
per_type_encoder_f VehicleID_encode_uper;
per_type_decoder_f VehicleID_decode_aper;
per_type_encoder_f VehicleID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleID_H_ */
#include <asn_internal.h>
