/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MVM-PDU-Descriptions"
 * 	found in "modified_MVM-PDU-Descriptions.asn"
 */

#ifndef	_VidResponse_H_
#define	_VidResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VidVehicleStateEnum.h"
#include "UInt64.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VidResponse */
typedef struct VidResponse {
	VidVehicleStateEnum_t	 vidVehicleState;
	UInt64_t	 vidVehiclePublicKey;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VidResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VidResponse;
extern asn_SEQUENCE_specifics_t asn_SPC_VidResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_VidResponse_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _VidResponse_H_ */
#include <asn_internal.h>
