/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EVCSN-PDU-Descriptions"
 * 	found in "preprocessed_temp/EVCSN-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/EVCSN_TS_101_556-1/Gen_File`
 */

#ifndef	_DigitalMap_H_
#define	_DigitalMap_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReferencePosition;

/* DigitalMap */
typedef struct DigitalMap {
	A_SEQUENCE_OF(struct ReferencePosition) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DigitalMap_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DigitalMap;
extern asn_SET_OF_specifics_t asn_SPC_DigitalMap_specs_1;
extern asn_TYPE_member_t asn_MBR_DigitalMap_1[1];
extern asn_per_constraints_t asn_PER_type_DigitalMap_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ReferencePosition.h"

#endif	/* _DigitalMap_H_ */
#include <asn_internal.h>
