/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/PIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/CP_TS104072/Gen_File`
 */

#include "ParkingSpaceDetections.h"

asn_TYPE_member_t asn_MBR_ParkingSpaceDetections_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ParkingSpaceDetections, individualParkingSpaces),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IndividualParkingSpaces,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"individualParkingSpaces"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ParkingSpaceDetections, segmentsOfParkingSpaces),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ParkingSpaceSegments,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"segmentsOfParkingSpaces"
		},
};
static const ber_tlv_tag_t asn_DEF_ParkingSpaceDetections_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ParkingSpaceDetections_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* individualParkingSpaces */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* segmentsOfParkingSpaces */
};
asn_SEQUENCE_specifics_t asn_SPC_ParkingSpaceDetections_specs_1 = {
	sizeof(struct ParkingSpaceDetections),
	offsetof(struct ParkingSpaceDetections, _asn_ctx),
	asn_MAP_ParkingSpaceDetections_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ParkingSpaceDetections = {
	"ParkingSpaceDetections",
	"ParkingSpaceDetections",
	&asn_OP_SEQUENCE,
	asn_DEF_ParkingSpaceDetections_tags_1,
	sizeof(asn_DEF_ParkingSpaceDetections_tags_1)
		/sizeof(asn_DEF_ParkingSpaceDetections_tags_1[0]), /* 1 */
	asn_DEF_ParkingSpaceDetections_tags_1,	/* Same as above */
	sizeof(asn_DEF_ParkingSpaceDetections_tags_1)
		/sizeof(asn_DEF_ParkingSpaceDetections_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ParkingSpaceDetections_1,
	2,	/* Elements count */
	&asn_SPC_ParkingSpaceDetections_specs_1	/* Additional specs */
};

