/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/PIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/CP_TS104072/Gen_File`
 */

#ifndef	_ParkingSpaceDetectionMetaData_H_
#define	_ParkingSpaceDetectionMetaData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier2B.h"
#include "StationId.h"
#include "TimestampIts.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ParkingSpaceDetectionMetaData */
typedef struct ParkingSpaceDetectionMetaData {
	Identifier2B_t	 id;
	StationId_t	*source;	/* OPTIONAL */
	TimestampIts_t	 endTime;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParkingSpaceDetectionMetaData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParkingSpaceDetectionMetaData;
extern asn_SEQUENCE_specifics_t asn_SPC_ParkingSpaceDetectionMetaData_specs_1;
extern asn_TYPE_member_t asn_MBR_ParkingSpaceDetectionMetaData_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ParkingSpaceDetectionMetaData_H_ */
#include <asn_internal.h>
