/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PIM-PDU-Descriptions"
 * 	found in "preprocessed_temp/PIM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/CP_TS104072/Gen_File`
 */

#ifndef	_ParkingSegments_H_
#define	_ParkingSegments_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ParkingSegment;

/* ParkingSegments */
typedef struct ParkingSegments {
	A_SEQUENCE_OF(struct ParkingSegment) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParkingSegments_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParkingSegments;
extern asn_SET_OF_specifics_t asn_SPC_ParkingSegments_specs_1;
extern asn_TYPE_member_t asn_MBR_ParkingSegments_1[1];
extern asn_per_constraints_t asn_PER_type_ParkingSegments_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ParkingSegment.h"

#endif	/* _ParkingSegments_H_ */
#include <asn_internal.h>
