/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SaeJ3287AsrBsm"
 * 	found in "preprocessed_temp/SaeJ3287AsrBsm.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_AsrBsm_H_
#define	_AsrBsm_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AsrBsm */
typedef NULL_t	 AsrBsm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AsrBsm;
asn_struct_free_f AsrBsm_free;
asn_struct_print_f AsrBsm_print;
asn_constr_check_f AsrBsm_constraint;
ber_type_decoder_f AsrBsm_decode_ber;
der_type_encoder_f AsrBsm_encode_der;
xer_type_decoder_f AsrBsm_decode_xer;
xer_type_encoder_f AsrBsm_encode_xer;
jer_type_encoder_f AsrBsm_encode_jer;
oer_type_decoder_f AsrBsm_decode_oer;
oer_type_encoder_f AsrBsm_encode_oer;
per_type_decoder_f AsrBsm_decode_uper;
per_type_encoder_f AsrBsm_encode_uper;
per_type_decoder_f AsrBsm_decode_aper;
per_type_encoder_f AsrBsm_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AsrBsm_H_ */
#include <asn_internal.h>
