/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759AsrCam"
 * 	found in "preprocessed_temp/EtsiTs103759AsrCam.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#include "AsrCam.h"

/*
 * This type is implemented using TemplateAsr_48P0,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_AsrCam_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_AsrCam = {
	"AsrCam",
	"AsrCam",
	&asn_OP_SEQUENCE,
	asn_DEF_AsrCam_tags_1,
	sizeof(asn_DEF_AsrCam_tags_1)
		/sizeof(asn_DEF_AsrCam_tags_1[0]), /* 1 */
	asn_DEF_AsrCam_tags_1,	/* Same as above */
	sizeof(asn_DEF_AsrCam_tags_1)
		/sizeof(asn_DEF_AsrCam_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_TemplateAsr_48P0_1,
	3,	/* Elements count */
	&asn_SPC_TemplateAsr_48P0_specs_1	/* Additional specs */
};

