/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759CommonObservations"
 * 	found in "preprocessed_temp/EtsiTs103759CommonObservations.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_Beacon_IntervalTooSmall_H_
#define	_Beacon_IntervalTooSmall_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Beacon-IntervalTooSmall */
typedef NULL_t	 Beacon_IntervalTooSmall_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Beacon_IntervalTooSmall;
asn_struct_free_f Beacon_IntervalTooSmall_free;
asn_struct_print_f Beacon_IntervalTooSmall_print;
asn_constr_check_f Beacon_IntervalTooSmall_constraint;
ber_type_decoder_f Beacon_IntervalTooSmall_decode_ber;
der_type_encoder_f Beacon_IntervalTooSmall_encode_der;
xer_type_decoder_f Beacon_IntervalTooSmall_decode_xer;
xer_type_encoder_f Beacon_IntervalTooSmall_encode_xer;
jer_type_encoder_f Beacon_IntervalTooSmall_encode_jer;
oer_type_decoder_f Beacon_IntervalTooSmall_decode_oer;
oer_type_encoder_f Beacon_IntervalTooSmall_encode_oer;
per_type_decoder_f Beacon_IntervalTooSmall_decode_uper;
per_type_encoder_f Beacon_IntervalTooSmall_encode_uper;
per_type_decoder_f Beacon_IntervalTooSmall_decode_aper;
per_type_encoder_f Beacon_IntervalTooSmall_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Beacon_IntervalTooSmall_H_ */
#include <asn_internal.h>
