/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759BaseTypes"
 * 	found in "preprocessed_temp/EtsiTs103759BaseTypes.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#include "C-ASR-SINGLE-OBS.h"

/*
 * This type is implemented using C_2ENT,
 * so here we adjust the DEF accordingly.
 */
asn_TYPE_descriptor_t asn_DEF_C_ASR_SINGLE_OBS = {
	"C-ASR-SINGLE-OBS",
	"C-ASR-SINGLE-OBS",
	&asn_OP_struct C_2ENT,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		struct C_2ENT_constraint
	},
	0, 0,	/* No members */
	0	/* No specifics */
};

