/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759BaseTypes"
 * 	found in "preprocessed_temp/EtsiTs103759BaseTypes.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_C_ASR_EV_H_
#define	_C_ASR_EV_H_


#include <asn_application.h>

/* Including external dependencies */
#include "C-2ENT.h"

#ifdef __cplusplus
extern "C" {
#endif

/* C-ASR-EV */
typedef C_2ENT_t	 C_ASR_EV_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_C_ASR_EV;
asn_struct_free_f C_ASR_EV_free;
asn_struct_print_f C_ASR_EV_print;
asn_constr_check_f C_ASR_EV_constraint;
ber_type_decoder_f C_ASR_EV_decode_ber;
der_type_encoder_f C_ASR_EV_encode_der;
xer_type_decoder_f C_ASR_EV_decode_xer;
xer_type_encoder_f C_ASR_EV_encode_xer;
jer_type_encoder_f C_ASR_EV_encode_jer;
oer_type_decoder_f C_ASR_EV_decode_oer;
oer_type_encoder_f C_ASR_EV_encode_oer;
per_type_decoder_f C_ASR_EV_decode_uper;
per_type_encoder_f C_ASR_EV_encode_uper;
per_type_decoder_f C_ASR_EV_decode_aper;
per_type_encoder_f C_ASR_EV_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _C_ASR_EV_H_ */
#include <asn_internal.h>
