/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759Core"
 * 	found in "preprocessed_temp/EtsiTs103759Core.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_EtsiTs103759Data_H_
#define	_EtsiTs103759Data_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"
#include "Time64.h"
#include "ThreeDLocation.h"
#include "AidSpecificReport.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EtsiTs103759Data */
typedef struct EtsiTs103759Data {
	Uint8_t	 version;
	Time64_t	 generationTime;
	ThreeDLocation_t	 observationLocation;
	AidSpecificReport_t	 report;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EtsiTs103759Data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EtsiTs103759Data;

#ifdef __cplusplus
}
#endif

#endif	/* _EtsiTs103759Data_H_ */
#include <asn_internal.h>
