/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103097ExtensionModule"
 * 	found in "preprocessed_temp/EtsiTs103097ExtensionModule.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_EtsiTs103097ExtensionModule_ExtId_H_
#define	_EtsiTs103097ExtensionModule_ExtId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EtsiTs103097ExtensionModule_ExtId */
typedef long	 EtsiTs103097ExtensionModule_ExtId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EtsiTs103097ExtensionModule_ExtId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EtsiTs103097ExtensionModule_ExtId;
asn_struct_free_f EtsiTs103097ExtensionModule_ExtId_free;
asn_struct_print_f EtsiTs103097ExtensionModule_ExtId_print;
asn_constr_check_f EtsiTs103097ExtensionModule_ExtId_constraint;
ber_type_decoder_f EtsiTs103097ExtensionModule_ExtId_decode_ber;
der_type_encoder_f EtsiTs103097ExtensionModule_ExtId_encode_der;
xer_type_decoder_f EtsiTs103097ExtensionModule_ExtId_decode_xer;
xer_type_encoder_f EtsiTs103097ExtensionModule_ExtId_encode_xer;
jer_type_encoder_f EtsiTs103097ExtensionModule_ExtId_encode_jer;
oer_type_decoder_f EtsiTs103097ExtensionModule_ExtId_decode_oer;
oer_type_encoder_f EtsiTs103097ExtensionModule_ExtId_encode_oer;
per_type_decoder_f EtsiTs103097ExtensionModule_ExtId_decode_uper;
per_type_encoder_f EtsiTs103097ExtensionModule_ExtId_encode_uper;
per_type_decoder_f EtsiTs103097ExtensionModule_ExtId_decode_aper;
per_type_encoder_f EtsiTs103097ExtensionModule_ExtId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EtsiTs103097ExtensionModule_ExtId_H_ */
#include <asn_internal.h>
