/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759CommonObservations"
 * 	found in "preprocessed_temp/EtsiTs103759CommonObservations.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_IdMbObs_H_
#define	_IdMbObs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"

#ifdef __cplusplus
extern "C" {
#endif

/* IdMbObs */
typedef Uint8_t	 IdMbObs_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_IdMbObs_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_IdMbObs;
asn_struct_free_f IdMbObs_free;
asn_struct_print_f IdMbObs_print;
asn_constr_check_f IdMbObs_constraint;
ber_type_decoder_f IdMbObs_decode_ber;
der_type_encoder_f IdMbObs_encode_der;
xer_type_decoder_f IdMbObs_decode_xer;
xer_type_encoder_f IdMbObs_encode_xer;
jer_type_encoder_f IdMbObs_encode_jer;
oer_type_decoder_f IdMbObs_decode_oer;
oer_type_encoder_f IdMbObs_encode_oer;
per_type_decoder_f IdMbObs_decode_uper;
per_type_encoder_f IdMbObs_encode_uper;
per_type_decoder_f IdMbObs_decode_aper;
per_type_encoder_f IdMbObs_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _IdMbObs_H_ */
#include <asn_internal.h>
