/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2CrlBaseTypes"
 * 	found in "preprocessed_temp/Ieee1609Dot2CrlBaseTypes.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_LvGenerationFunctionIdentifier_H_
#define	_LvGenerationFunctionIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LvGenerationFunctionIdentifier */
typedef NULL_t	 LvGenerationFunctionIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LvGenerationFunctionIdentifier;
asn_struct_free_f LvGenerationFunctionIdentifier_free;
asn_struct_print_f LvGenerationFunctionIdentifier_print;
asn_constr_check_f LvGenerationFunctionIdentifier_constraint;
ber_type_decoder_f LvGenerationFunctionIdentifier_decode_ber;
der_type_encoder_f LvGenerationFunctionIdentifier_encode_der;
xer_type_decoder_f LvGenerationFunctionIdentifier_decode_xer;
xer_type_encoder_f LvGenerationFunctionIdentifier_encode_xer;
jer_type_encoder_f LvGenerationFunctionIdentifier_encode_jer;
oer_type_decoder_f LvGenerationFunctionIdentifier_decode_oer;
oer_type_encoder_f LvGenerationFunctionIdentifier_encode_oer;
per_type_decoder_f LvGenerationFunctionIdentifier_decode_uper;
per_type_encoder_f LvGenerationFunctionIdentifier_encode_uper;
per_type_decoder_f LvGenerationFunctionIdentifier_decode_aper;
per_type_encoder_f LvGenerationFunctionIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LvGenerationFunctionIdentifier_H_ */
#include <asn_internal.h>
