/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759BaseTypes"
 * 	found in "preprocessed_temp/EtsiTs103759BaseTypes.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#include "MbSingleObservation.h"

static const long asn_VAL_1_c_ObsBeacon_IntervalTooSmall = 1;
static const asn_ioc_cell_t asn_IOS_SetMbObsCamBeacon_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_1_c_ObsBeacon_IntervalTooSmall },
	{ "&Val", aioc__type, &asn_DEF_Beacon_IntervalTooSmall }
};
static const asn_ioc_set_t asn_IOS_SetMbObsCamBeacon_1[] = {
	{ 1, 2, asn_IOS_SetMbObsCamBeacon_1_rows }
};
static const long asn_VAL_2_c_ObsStatic_Change = 1;
static const asn_ioc_cell_t asn_IOS_SetMbObsCamStatic_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_2_c_ObsStatic_Change },
	{ "&Val", aioc__type, &asn_DEF_Static_Change }
};
static const asn_ioc_set_t asn_IOS_SetMbObsCamStatic_1[] = {
	{ 1, 2, asn_IOS_SetMbObsCamStatic_1_rows }
};
static const long asn_VAL_3_c_ObsSecurity_MessageIdIncWithHeaderInfo = 1;
static const long asn_VAL_4_c_ObsSecurity_HeaderIncWithSecurityProfile = 2;
static const long asn_VAL_5_c_ObsSecurity_HeaderPsidIncWithCertificate = 3;
static const long asn_VAL_6_c_ObsSecurity_MessageIncWithSsp = 4;
static const long asn_VAL_7_c_ObsSecurity_HeaderTimeOutsideCertificateValidity = 5;
static const long asn_VAL_8_c_ObsSecurity_MessageLocationOutsideCertificateValidity = 6;
static const long asn_VAL_9_c_ObsSecurity_HeaderLocationOutsideCertificateValidity = 7;
static const asn_ioc_cell_t asn_IOS_SetMbObsCamSecurity_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_3_c_ObsSecurity_MessageIdIncWithHeaderInfo },
	{ "&Val", aioc__type, &asn_DEF_Security_MessageIdIncWithHeaderInfo },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_4_c_ObsSecurity_HeaderIncWithSecurityProfile },
	{ "&Val", aioc__type, &asn_DEF_Security_HeaderIncWithSecurityProfile },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_5_c_ObsSecurity_HeaderPsidIncWithCertificate },
	{ "&Val", aioc__type, &asn_DEF_Security_HeaderPsidIncWithCertificate },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_6_c_ObsSecurity_MessageIncWithSsp },
	{ "&Val", aioc__type, &asn_DEF_Security_MessageIncWithSsp },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_7_c_ObsSecurity_HeaderTimeOutsideCertificateValidity },
	{ "&Val", aioc__type, &asn_DEF_Security_HeaderTimeOutsideCertificateValidity },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_8_c_ObsSecurity_MessageLocationOutsideCertificateValidity },
	{ "&Val", aioc__type, &asn_DEF_Security_MessageLocationOutsideCertificateValidity },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_9_c_ObsSecurity_HeaderLocationOutsideCertificateValidity },
	{ "&Val", aioc__type, &asn_DEF_Security_HeaderLocationOutsideCertificateValidity }
};
static const asn_ioc_set_t asn_IOS_SetMbObsCamSecurity_1[] = {
	{ 7, 2, asn_IOS_SetMbObsCamSecurity_1_rows }
};
static const long asn_VAL_10_c_ObsPosition_ChangeTooLarge = 4;
static const asn_ioc_cell_t asn_IOS_SetMbObsCamPosition_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_10_c_ObsPosition_ChangeTooLarge },
	{ "&Val", aioc__type, &asn_DEF_Position_ChangeTooLarge }
};
static const asn_ioc_set_t asn_IOS_SetMbObsCamPosition_1[] = {
	{ 1, 2, asn_IOS_SetMbObsCamPosition_1_rows }
};
static const long asn_VAL_11_c_ObsSpeed_ValueTooLarge_VehicleType = 3;
static const long asn_VAL_12_c_ObsSpeed_ValueTooLarge_DriveDirectionReverse = 4;
static const long asn_VAL_13_c_ObsSpeed_ChangeTooLarge = 5;
static const asn_ioc_cell_t asn_IOS_SetMbObsCamSpeed_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_11_c_ObsSpeed_ValueTooLarge_VehicleType },
	{ "&Val", aioc__type, &asn_DEF_Speed_ValueTooLarge_VehicleType },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_12_c_ObsSpeed_ValueTooLarge_DriveDirectionReverse },
	{ "&Val", aioc__type, &asn_DEF_Speed_ValueTooLarge_DriveDirectionReverse },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_13_c_ObsSpeed_ChangeTooLarge },
	{ "&Val", aioc__type, &asn_DEF_Speed_ChangeTooLarge }
};
static const asn_ioc_set_t asn_IOS_SetMbObsCamSpeed_1[] = {
	{ 3, 2, asn_IOS_SetMbObsCamSpeed_1_rows }
};
static const long asn_VAL_14_c_ObsLongAcc_ValueTooLarge = 4;
static const asn_ioc_cell_t asn_IOS_SetMbObsCamLongAcc_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_14_c_ObsLongAcc_ValueTooLarge },
	{ "&Val", aioc__type, &asn_DEF_LongAcc_ValueTooLarge }
};
static const asn_ioc_set_t asn_IOS_SetMbObsCamLongAcc_1[] = {
	{ 1, 2, asn_IOS_SetMbObsCamLongAcc_1_rows }
};
static int
memb_obsId_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 255L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_SetMbObsCamBeacon_obs_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_SetMbObsCamBeacon_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &Val */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct SetMbObsCamBeacon, obsId));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_obs_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_obsId_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 255L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_SetMbObsCamStatic_obs_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_SetMbObsCamStatic_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &Val */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct SetMbObsCamStatic, obsId));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_obs_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_obsId_constraint_7(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 255L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_SetMbObsCamSecurity_obs_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_SetMbObsCamSecurity_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &Val */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct SetMbObsCamSecurity, obsId));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_obs_constraint_7(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_obsId_constraint_10(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 255L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_SetMbObsCamPosition_obs_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_SetMbObsCamPosition_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &Val */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct SetMbObsCamPosition, obsId));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_obs_constraint_10(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_obsId_constraint_13(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 255L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_SetMbObsCamSpeed_obs_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_SetMbObsCamSpeed_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &Val */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct SetMbObsCamSpeed, obsId));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_obs_constraint_13(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_obsId_constraint_16(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 255L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_SetMbObsCamLongAcc_obs_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_SetMbObsCamLongAcc_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &Val */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct SetMbObsCamLongAcc, obsId));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_obs_constraint_16(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_obsId_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_obsId_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_obs_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_obs_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_obsId_constr_5 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_obsId_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_obs_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_obs_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_obsId_constr_8 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_obsId_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_obs_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_obs_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_obsId_constr_11 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_obsId_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_obs_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_obs_constr_12 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_obsId_constr_14 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_obsId_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_obs_constr_15 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_obs_constr_15 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_obsId_constr_17 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_obsId_constr_17 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_obs_constr_18 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_obs_constr_18 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_obs_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamBeacon__obs, Beacon_IntervalTooSmall),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_Beacon_IntervalTooSmall,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Beacon-IntervalTooSmall"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_obs_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 0, 0, 0 } /* Beacon-IntervalTooSmall */
};
static asn_CHOICE_specifics_t asn_SPC_obs_specs_3 = {
	sizeof(struct SetMbObsCamBeacon__obs),
	offsetof(struct SetMbObsCamBeacon__obs, _asn_ctx),
	offsetof(struct SetMbObsCamBeacon__obs, present),
	sizeof(((struct SetMbObsCamBeacon__obs *)0)->present),
	asn_MAP_obs_tag2el_3,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_obs_3 = {
	"obs",
	"obs",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		OPEN_TYPE_constraint
	},
	asn_MBR_obs_3,
	1,	/* Elements count */
	&asn_SPC_obs_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SetMbObsCamBeacon_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamBeacon, obsId),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Uint8,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_obsId_constr_2,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_obsId_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_obsId_constraint_1
		},
		0, 0, /* No default value */
		"obsId"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamBeacon, obs),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_obs_3,
		select_SetMbObsCamBeacon_obs_type,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_obs_constr_3,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_obs_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_obs_constraint_1
		},
		0, 0, /* No default value */
		"obs"
		},
};
static const ber_tlv_tag_t asn_DEF_SetMbObsCamBeacon_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SetMbObsCamBeacon_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* obsId */
};
asn_SEQUENCE_specifics_t asn_SPC_SetMbObsCamBeacon_specs_1 = {
	sizeof(struct SetMbObsCamBeacon),
	offsetof(struct SetMbObsCamBeacon, _asn_ctx),
	asn_MAP_SetMbObsCamBeacon_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SetMbObsCamBeacon = {
	"SetMbObsCamBeacon",
	"SetMbObsCamBeacon",
	&asn_OP_SEQUENCE,
	asn_DEF_SetMbObsCamBeacon_tags_1,
	sizeof(asn_DEF_SetMbObsCamBeacon_tags_1)
		/sizeof(asn_DEF_SetMbObsCamBeacon_tags_1[0]), /* 1 */
	asn_DEF_SetMbObsCamBeacon_tags_1,	/* Same as above */
	sizeof(asn_DEF_SetMbObsCamBeacon_tags_1)
		/sizeof(asn_DEF_SetMbObsCamBeacon_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SetMbObsCamBeacon_1,
	2,	/* Elements count */
	&asn_SPC_SetMbObsCamBeacon_specs_1	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_obs_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamStatic__obs, Static_Change),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_Static_Change,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Static-Change"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_obs_tag2el_6[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 0, 0, 0 } /* Static-Change */
};
static asn_CHOICE_specifics_t asn_SPC_obs_specs_6 = {
	sizeof(struct SetMbObsCamStatic__obs),
	offsetof(struct SetMbObsCamStatic__obs, _asn_ctx),
	offsetof(struct SetMbObsCamStatic__obs, present),
	sizeof(((struct SetMbObsCamStatic__obs *)0)->present),
	asn_MAP_obs_tag2el_6,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_obs_6 = {
	"obs",
	"obs",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		OPEN_TYPE_constraint
	},
	asn_MBR_obs_6,
	1,	/* Elements count */
	&asn_SPC_obs_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SetMbObsCamStatic_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamStatic, obsId),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Uint8,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_obsId_constr_5,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_obsId_constr_5,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_obsId_constraint_4
		},
		0, 0, /* No default value */
		"obsId"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamStatic, obs),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_obs_6,
		select_SetMbObsCamStatic_obs_type,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_obs_constr_6,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_obs_constr_6,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_obs_constraint_4
		},
		0, 0, /* No default value */
		"obs"
		},
};
static const ber_tlv_tag_t asn_DEF_SetMbObsCamStatic_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SetMbObsCamStatic_tag2el_4[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* obsId */
};
asn_SEQUENCE_specifics_t asn_SPC_SetMbObsCamStatic_specs_4 = {
	sizeof(struct SetMbObsCamStatic),
	offsetof(struct SetMbObsCamStatic, _asn_ctx),
	asn_MAP_SetMbObsCamStatic_tag2el_4,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SetMbObsCamStatic = {
	"SetMbObsCamStatic",
	"SetMbObsCamStatic",
	&asn_OP_SEQUENCE,
	asn_DEF_SetMbObsCamStatic_tags_4,
	sizeof(asn_DEF_SetMbObsCamStatic_tags_4)
		/sizeof(asn_DEF_SetMbObsCamStatic_tags_4[0]), /* 1 */
	asn_DEF_SetMbObsCamStatic_tags_4,	/* Same as above */
	sizeof(asn_DEF_SetMbObsCamStatic_tags_4)
		/sizeof(asn_DEF_SetMbObsCamStatic_tags_4[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SetMbObsCamStatic_4,
	2,	/* Elements count */
	&asn_SPC_SetMbObsCamStatic_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_obs_9[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSecurity__obs, Security_MessageIdIncWithHeaderInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_Security_MessageIdIncWithHeaderInfo,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Security-MessageIdIncWithHeaderInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSecurity__obs, Security_HeaderIncWithSecurityProfile),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_Security_HeaderIncWithSecurityProfile,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Security-HeaderIncWithSecurityProfile"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSecurity__obs, Security_HeaderPsidIncWithCertificate),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_Security_HeaderPsidIncWithCertificate,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Security-HeaderPsidIncWithCertificate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSecurity__obs, Security_MessageIncWithSsp),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_Security_MessageIncWithSsp,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Security-MessageIncWithSsp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSecurity__obs, Security_HeaderTimeOutsideCertificateValidity),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_Security_HeaderTimeOutsideCertificateValidity,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Security-HeaderTimeOutsideCertificateValidity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSecurity__obs, Security_MessageLocationOutsideCertificateValidity),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_Security_MessageLocationOutsideCertificateValidity,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Security-MessageLocationOutsideCertificateValidity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSecurity__obs, Security_HeaderLocationOutsideCertificateValidity),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_Security_HeaderLocationOutsideCertificateValidity,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Security-HeaderLocationOutsideCertificateValidity"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_obs_tag2el_9[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 0, 0, 6 }, /* Security-MessageIdIncWithHeaderInfo */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 1, -1, 5 }, /* Security-HeaderIncWithSecurityProfile */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 2, -2, 4 }, /* Security-HeaderPsidIncWithCertificate */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 3, -3, 3 }, /* Security-MessageIncWithSsp */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 4, -4, 2 }, /* Security-HeaderTimeOutsideCertificateValidity */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 5, -5, 1 }, /* Security-MessageLocationOutsideCertificateValidity */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 6, -6, 0 } /* Security-HeaderLocationOutsideCertificateValidity */
};
static asn_CHOICE_specifics_t asn_SPC_obs_specs_9 = {
	sizeof(struct SetMbObsCamSecurity__obs),
	offsetof(struct SetMbObsCamSecurity__obs, _asn_ctx),
	offsetof(struct SetMbObsCamSecurity__obs, present),
	sizeof(((struct SetMbObsCamSecurity__obs *)0)->present),
	asn_MAP_obs_tag2el_9,
	7,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_obs_9 = {
	"obs",
	"obs",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		OPEN_TYPE_constraint
	},
	asn_MBR_obs_9,
	7,	/* Elements count */
	&asn_SPC_obs_specs_9	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SetMbObsCamSecurity_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSecurity, obsId),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Uint8,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_obsId_constr_8,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_obsId_constr_8,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_obsId_constraint_7
		},
		0, 0, /* No default value */
		"obsId"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSecurity, obs),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_obs_9,
		select_SetMbObsCamSecurity_obs_type,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_obs_constr_9,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_obs_constr_9,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_obs_constraint_7
		},
		0, 0, /* No default value */
		"obs"
		},
};
static const ber_tlv_tag_t asn_DEF_SetMbObsCamSecurity_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SetMbObsCamSecurity_tag2el_7[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* obsId */
};
asn_SEQUENCE_specifics_t asn_SPC_SetMbObsCamSecurity_specs_7 = {
	sizeof(struct SetMbObsCamSecurity),
	offsetof(struct SetMbObsCamSecurity, _asn_ctx),
	asn_MAP_SetMbObsCamSecurity_tag2el_7,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SetMbObsCamSecurity = {
	"SetMbObsCamSecurity",
	"SetMbObsCamSecurity",
	&asn_OP_SEQUENCE,
	asn_DEF_SetMbObsCamSecurity_tags_7,
	sizeof(asn_DEF_SetMbObsCamSecurity_tags_7)
		/sizeof(asn_DEF_SetMbObsCamSecurity_tags_7[0]), /* 1 */
	asn_DEF_SetMbObsCamSecurity_tags_7,	/* Same as above */
	sizeof(asn_DEF_SetMbObsCamSecurity_tags_7)
		/sizeof(asn_DEF_SetMbObsCamSecurity_tags_7[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SetMbObsCamSecurity_7,
	2,	/* Elements count */
	&asn_SPC_SetMbObsCamSecurity_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_obs_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamPosition__obs, Position_ChangeTooLarge),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_Position_ChangeTooLarge,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Position-ChangeTooLarge"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_obs_tag2el_12[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 0, 0, 0 } /* Position-ChangeTooLarge */
};
static asn_CHOICE_specifics_t asn_SPC_obs_specs_12 = {
	sizeof(struct SetMbObsCamPosition__obs),
	offsetof(struct SetMbObsCamPosition__obs, _asn_ctx),
	offsetof(struct SetMbObsCamPosition__obs, present),
	sizeof(((struct SetMbObsCamPosition__obs *)0)->present),
	asn_MAP_obs_tag2el_12,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_obs_12 = {
	"obs",
	"obs",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		OPEN_TYPE_constraint
	},
	asn_MBR_obs_12,
	1,	/* Elements count */
	&asn_SPC_obs_specs_12	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SetMbObsCamPosition_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamPosition, obsId),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Uint8,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_obsId_constr_11,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_obsId_constr_11,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_obsId_constraint_10
		},
		0, 0, /* No default value */
		"obsId"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamPosition, obs),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_obs_12,
		select_SetMbObsCamPosition_obs_type,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_obs_constr_12,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_obs_constr_12,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_obs_constraint_10
		},
		0, 0, /* No default value */
		"obs"
		},
};
static const ber_tlv_tag_t asn_DEF_SetMbObsCamPosition_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SetMbObsCamPosition_tag2el_10[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* obsId */
};
asn_SEQUENCE_specifics_t asn_SPC_SetMbObsCamPosition_specs_10 = {
	sizeof(struct SetMbObsCamPosition),
	offsetof(struct SetMbObsCamPosition, _asn_ctx),
	asn_MAP_SetMbObsCamPosition_tag2el_10,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SetMbObsCamPosition = {
	"SetMbObsCamPosition",
	"SetMbObsCamPosition",
	&asn_OP_SEQUENCE,
	asn_DEF_SetMbObsCamPosition_tags_10,
	sizeof(asn_DEF_SetMbObsCamPosition_tags_10)
		/sizeof(asn_DEF_SetMbObsCamPosition_tags_10[0]), /* 1 */
	asn_DEF_SetMbObsCamPosition_tags_10,	/* Same as above */
	sizeof(asn_DEF_SetMbObsCamPosition_tags_10)
		/sizeof(asn_DEF_SetMbObsCamPosition_tags_10[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SetMbObsCamPosition_10,
	2,	/* Elements count */
	&asn_SPC_SetMbObsCamPosition_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_obs_15[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSpeed__obs, Speed_ValueTooLarge_VehicleType),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_Speed_ValueTooLarge_VehicleType,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Speed-ValueTooLarge-VehicleType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSpeed__obs, Speed_ValueTooLarge_DriveDirectionReverse),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_Speed_ValueTooLarge_DriveDirectionReverse,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Speed-ValueTooLarge-DriveDirectionReverse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSpeed__obs, Speed_ChangeTooLarge),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_Speed_ChangeTooLarge,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Speed-ChangeTooLarge"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_obs_tag2el_15[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 0, 0, 2 }, /* Speed-ValueTooLarge-VehicleType */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 1, -1, 1 }, /* Speed-ValueTooLarge-DriveDirectionReverse */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 2, -2, 0 } /* Speed-ChangeTooLarge */
};
static asn_CHOICE_specifics_t asn_SPC_obs_specs_15 = {
	sizeof(struct SetMbObsCamSpeed__obs),
	offsetof(struct SetMbObsCamSpeed__obs, _asn_ctx),
	offsetof(struct SetMbObsCamSpeed__obs, present),
	sizeof(((struct SetMbObsCamSpeed__obs *)0)->present),
	asn_MAP_obs_tag2el_15,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_obs_15 = {
	"obs",
	"obs",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		OPEN_TYPE_constraint
	},
	asn_MBR_obs_15,
	3,	/* Elements count */
	&asn_SPC_obs_specs_15	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SetMbObsCamSpeed_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSpeed, obsId),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Uint8,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_obsId_constr_14,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_obsId_constr_14,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_obsId_constraint_13
		},
		0, 0, /* No default value */
		"obsId"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamSpeed, obs),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_obs_15,
		select_SetMbObsCamSpeed_obs_type,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_obs_constr_15,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_obs_constr_15,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_obs_constraint_13
		},
		0, 0, /* No default value */
		"obs"
		},
};
static const ber_tlv_tag_t asn_DEF_SetMbObsCamSpeed_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SetMbObsCamSpeed_tag2el_13[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* obsId */
};
asn_SEQUENCE_specifics_t asn_SPC_SetMbObsCamSpeed_specs_13 = {
	sizeof(struct SetMbObsCamSpeed),
	offsetof(struct SetMbObsCamSpeed, _asn_ctx),
	asn_MAP_SetMbObsCamSpeed_tag2el_13,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SetMbObsCamSpeed = {
	"SetMbObsCamSpeed",
	"SetMbObsCamSpeed",
	&asn_OP_SEQUENCE,
	asn_DEF_SetMbObsCamSpeed_tags_13,
	sizeof(asn_DEF_SetMbObsCamSpeed_tags_13)
		/sizeof(asn_DEF_SetMbObsCamSpeed_tags_13[0]), /* 1 */
	asn_DEF_SetMbObsCamSpeed_tags_13,	/* Same as above */
	sizeof(asn_DEF_SetMbObsCamSpeed_tags_13)
		/sizeof(asn_DEF_SetMbObsCamSpeed_tags_13[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SetMbObsCamSpeed_13,
	2,	/* Elements count */
	&asn_SPC_SetMbObsCamSpeed_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_obs_18[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamLongAcc__obs, LongAcc_ValueTooLarge),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_LongAcc_ValueTooLarge,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"LongAcc-ValueTooLarge"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_obs_tag2el_18[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 0, 0, 0 } /* LongAcc-ValueTooLarge */
};
static asn_CHOICE_specifics_t asn_SPC_obs_specs_18 = {
	sizeof(struct SetMbObsCamLongAcc__obs),
	offsetof(struct SetMbObsCamLongAcc__obs, _asn_ctx),
	offsetof(struct SetMbObsCamLongAcc__obs, present),
	sizeof(((struct SetMbObsCamLongAcc__obs *)0)->present),
	asn_MAP_obs_tag2el_18,
	1,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_obs_18 = {
	"obs",
	"obs",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		OPEN_TYPE_constraint
	},
	asn_MBR_obs_18,
	1,	/* Elements count */
	&asn_SPC_obs_specs_18	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SetMbObsCamLongAcc_16[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamLongAcc, obsId),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Uint8,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_obsId_constr_17,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_obsId_constr_17,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_obsId_constraint_16
		},
		0, 0, /* No default value */
		"obsId"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct SetMbObsCamLongAcc, obs),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_obs_18,
		select_SetMbObsCamLongAcc_obs_type,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_obs_constr_18,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_obs_constr_18,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_obs_constraint_16
		},
		0, 0, /* No default value */
		"obs"
		},
};
static const ber_tlv_tag_t asn_DEF_SetMbObsCamLongAcc_tags_16[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SetMbObsCamLongAcc_tag2el_16[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* obsId */
};
asn_SEQUENCE_specifics_t asn_SPC_SetMbObsCamLongAcc_specs_16 = {
	sizeof(struct SetMbObsCamLongAcc),
	offsetof(struct SetMbObsCamLongAcc, _asn_ctx),
	asn_MAP_SetMbObsCamLongAcc_tag2el_16,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SetMbObsCamLongAcc = {
	"SetMbObsCamLongAcc",
	"SetMbObsCamLongAcc",
	&asn_OP_SEQUENCE,
	asn_DEF_SetMbObsCamLongAcc_tags_16,
	sizeof(asn_DEF_SetMbObsCamLongAcc_tags_16)
		/sizeof(asn_DEF_SetMbObsCamLongAcc_tags_16[0]), /* 1 */
	asn_DEF_SetMbObsCamLongAcc_tags_16,	/* Same as above */
	sizeof(asn_DEF_SetMbObsCamLongAcc_tags_16)
		/sizeof(asn_DEF_SetMbObsCamLongAcc_tags_16[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SetMbObsCamLongAcc_16,
	2,	/* Elements count */
	&asn_SPC_SetMbObsCamLongAcc_specs_16	/* Additional specs */
};

