/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759BaseTypes"
 * 	found in "preprocessed_temp/EtsiTs103759BaseTypes.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_NonV2xPduEvidenceItemSequence_H_
#define	_NonV2xPduEvidenceItemSequence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SetMbEvCam;

/* NonV2xPduEvidenceItemSequence */
typedef struct NonV2xPduEvidenceItemSequence_183P0 {
	A_SEQUENCE_OF(struct SetMbEvCam) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NonV2xPduEvidenceItemSequence_183P0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NonV2xPduEvidenceItemSequence_183P0;
extern asn_SET_OF_specifics_t asn_SPC_NonV2xPduEvidenceItemSequence_183P0_specs_1;
extern asn_TYPE_member_t asn_MBR_NonV2xPduEvidenceItemSequence_183P0_1[1];
extern asn_per_constraints_t asn_PER_type_NonV2xPduEvidenceItemSequence_183P0_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NonV2xPduEvidenceItem.h"

#endif	/* _NonV2xPduEvidenceItemSequence_H_ */
#include <asn_internal.h>
