/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759BaseTypes"
 * 	found in "preprocessed_temp/EtsiTs103759BaseTypes.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_ObservationsByTarget_H_
#define	_ObservationsByTarget_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"
#include <asn_ioc.h>
#include "SetMbObsCamBeacon.h"
#include "SetMbObsCamStatic.h"
#include "SetMbObsCamSecurity.h"
#include "SetMbObsCamPosition.h"
#include "SetMbObsCamSpeed.h"
#include "SetMbObsCamLongAcc.h"
#include <ANY.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ObservationsByTarget */
typedef struct SetMbObsTgtsCam {
	Uint8_t	 tgtId;
	struct SetMbObsTgtsCam__observations {
		A_SEQUENCE_OF(ANY_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} observations;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetMbObsTgtsCam_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetMbObsTgtsCam;
extern asn_SEQUENCE_specifics_t asn_SPC_SetMbObsTgtsCam_specs_1;
extern asn_TYPE_member_t asn_MBR_SetMbObsTgtsCam_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ObservationsByTarget_H_ */
#include <asn_internal.h>
