/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759BaseTypes"
 * 	found in "preprocessed_temp/EtsiTs103759BaseTypes.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#include "ObservationsByTarget.h"

static const long asn_VAL_15_c_CamTgt_BeaconCommon = 0;
static const long asn_VAL_16_c_CamTgt_StaticCommon = 1;
static const long asn_VAL_17_c_CamTgt_SecurityCommon = 2;
static const long asn_VAL_18_c_CamTgt_PositionCommon = 3;
static const long asn_VAL_19_c_CamTgt_SpeedCommon = 4;
static const long asn_VAL_20_c_CamTgt_LongAccCommon = 5;
static const asn_ioc_cell_t asn_IOS_SetMbObsTgtsCam_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_15_c_CamTgt_BeaconCommon },
	{ "&Val", aioc__type, &asn_DEF_MbSingleObservation },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_16_c_CamTgt_StaticCommon },
	{ "&Val", aioc__type, &asn_DEF_MbSingleObservation },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_17_c_CamTgt_SecurityCommon },
	{ "&Val", aioc__type, &asn_DEF_MbSingleObservation },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_18_c_CamTgt_PositionCommon },
	{ "&Val", aioc__type, &asn_DEF_MbSingleObservation },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_19_c_CamTgt_SpeedCommon },
	{ "&Val", aioc__type, &asn_DEF_MbSingleObservation },
	{ "&id", aioc__value, &asn_DEF_Uint8, &asn_VAL_20_c_CamTgt_LongAccCommon },
	{ "&Val", aioc__type, &asn_DEF_MbSingleObservation }
};
static const asn_ioc_set_t asn_IOS_SetMbObsTgtsCam_1[] = {
	{ 6, 2, asn_IOS_SetMbObsTgtsCam_1_rows }
};
static int
memb_ANY_constraint_3(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_tgtId_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 255L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_Member_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_Member_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_tgtId_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_tgtId_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_observations_3[] = {
	{ ATF_ANY_TYPE | ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_Member_constr_4,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_Member_constr_4,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_ANY_constraint_3
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_observations_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_observations_specs_3 = {
	sizeof(struct SetMbObsTgtsCam__observations),
	offsetof(struct SetMbObsTgtsCam__observations, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_observations_3 = {
	"observations",
	"observations",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_observations_tags_3,
	sizeof(asn_DEF_observations_tags_3)
		/sizeof(asn_DEF_observations_tags_3[0]), /* 1 */
	asn_DEF_observations_tags_3,	/* Same as above */
	sizeof(asn_DEF_observations_tags_3)
		/sizeof(asn_DEF_observations_tags_3[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_observations_3,
	1,	/* Single element */
	&asn_SPC_observations_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SetMbObsTgtsCam_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsTgtsCam, tgtId),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Uint8,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_tgtId_constr_2,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_tgtId_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_tgtId_constraint_1
		},
		0, 0, /* No default value */
		"tgtId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetMbObsTgtsCam, observations),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_observations_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"observations"
		},
};
static const ber_tlv_tag_t asn_DEF_SetMbObsTgtsCam_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SetMbObsTgtsCam_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* tgtId */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* observations */
};
asn_SEQUENCE_specifics_t asn_SPC_SetMbObsTgtsCam_specs_1 = {
	sizeof(struct SetMbObsTgtsCam),
	offsetof(struct SetMbObsTgtsCam, _asn_ctx),
	asn_MAP_SetMbObsTgtsCam_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SetMbObsTgtsCam = {
	"SetMbObsTgtsCam",
	"SetMbObsTgtsCam",
	&asn_OP_SEQUENCE,
	asn_DEF_SetMbObsTgtsCam_tags_1,
	sizeof(asn_DEF_SetMbObsTgtsCam_tags_1)
		/sizeof(asn_DEF_SetMbObsTgtsCam_tags_1[0]), /* 1 */
	asn_DEF_SetMbObsTgtsCam_tags_1,	/* Same as above */
	sizeof(asn_DEF_SetMbObsTgtsCam_tags_1)
		/sizeof(asn_DEF_SetMbObsTgtsCam_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SetMbObsTgtsCam_1,
	2,	/* Elements count */
	&asn_SPC_SetMbObsTgtsCam_specs_1	/* Additional specs */
};

