/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759CommonObservations"
 * 	found in "preprocessed_temp/EtsiTs103759CommonObservations.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_Security_MessageIncWithSsp_H_
#define	_Security_MessageIncWithSsp_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Security-MessageIncWithSsp */
typedef NULL_t	 Security_MessageIncWithSsp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Security_MessageIncWithSsp;
asn_struct_free_f Security_MessageIncWithSsp_free;
asn_struct_print_f Security_MessageIncWithSsp_print;
asn_constr_check_f Security_MessageIncWithSsp_constraint;
ber_type_decoder_f Security_MessageIncWithSsp_decode_ber;
der_type_encoder_f Security_MessageIncWithSsp_encode_der;
xer_type_decoder_f Security_MessageIncWithSsp_decode_xer;
xer_type_encoder_f Security_MessageIncWithSsp_encode_xer;
jer_type_encoder_f Security_MessageIncWithSsp_encode_jer;
oer_type_decoder_f Security_MessageIncWithSsp_decode_oer;
oer_type_encoder_f Security_MessageIncWithSsp_encode_oer;
per_type_decoder_f Security_MessageIncWithSsp_decode_uper;
per_type_encoder_f Security_MessageIncWithSsp_encode_uper;
per_type_decoder_f Security_MessageIncWithSsp_decode_aper;
per_type_encoder_f Security_MessageIncWithSsp_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Security_MessageIncWithSsp_H_ */
#include <asn_internal.h>
