/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759CommonObservations"
 * 	found in "preprocessed_temp/EtsiTs103759CommonObservations.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_Speed_ValueTooLarge_DriveDirectionReverse_H_
#define	_Speed_ValueTooLarge_DriveDirectionReverse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Speed-ValueTooLarge-DriveDirectionReverse */
typedef NULL_t	 Speed_ValueTooLarge_DriveDirectionReverse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Speed_ValueTooLarge_DriveDirectionReverse;
asn_struct_free_f Speed_ValueTooLarge_DriveDirectionReverse_free;
asn_struct_print_f Speed_ValueTooLarge_DriveDirectionReverse_print;
asn_constr_check_f Speed_ValueTooLarge_DriveDirectionReverse_constraint;
ber_type_decoder_f Speed_ValueTooLarge_DriveDirectionReverse_decode_ber;
der_type_encoder_f Speed_ValueTooLarge_DriveDirectionReverse_encode_der;
xer_type_decoder_f Speed_ValueTooLarge_DriveDirectionReverse_decode_xer;
xer_type_encoder_f Speed_ValueTooLarge_DriveDirectionReverse_encode_xer;
jer_type_encoder_f Speed_ValueTooLarge_DriveDirectionReverse_encode_jer;
oer_type_decoder_f Speed_ValueTooLarge_DriveDirectionReverse_decode_oer;
oer_type_encoder_f Speed_ValueTooLarge_DriveDirectionReverse_encode_oer;
per_type_decoder_f Speed_ValueTooLarge_DriveDirectionReverse_decode_uper;
per_type_encoder_f Speed_ValueTooLarge_DriveDirectionReverse_encode_uper;
per_type_decoder_f Speed_ValueTooLarge_DriveDirectionReverse_decode_aper;
per_type_encoder_f Speed_ValueTooLarge_DriveDirectionReverse_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Speed_ValueTooLarge_DriveDirectionReverse_H_ */
#include <asn_internal.h>
