/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759CommonObservations"
 * 	found in "preprocessed_temp/EtsiTs103759CommonObservations.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_Static_Change_H_
#define	_Static_Change_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Static-Change */
typedef BIT_STRING_t	 Static_Change_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Static_Change;
asn_struct_free_f Static_Change_free;
asn_struct_print_f Static_Change_print;
asn_constr_check_f Static_Change_constraint;
ber_type_decoder_f Static_Change_decode_ber;
der_type_encoder_f Static_Change_encode_der;
xer_type_decoder_f Static_Change_decode_xer;
xer_type_encoder_f Static_Change_encode_xer;
jer_type_encoder_f Static_Change_encode_jer;
oer_type_decoder_f Static_Change_decode_oer;
oer_type_encoder_f Static_Change_encode_oer;
per_type_decoder_f Static_Change_decode_uper;
per_type_encoder_f Static_Change_encode_uper;
per_type_decoder_f Static_Change_decode_aper;
per_type_encoder_f Static_Change_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Static_Change_H_ */
#include <asn_internal.h>
