/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759CommonObservations"
 * 	found in "preprocessed_temp/EtsiTs103759CommonObservations.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#include "Static-Change.h"

/*
 * This type is implemented using BIT_STRING,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_JER_SUPPORT)
static asn_jer_constraints_t asn_JER_type_Static_Change_constr_1 CC_NOTUSED = {
	-1};
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
static const ber_tlv_tag_t asn_DEF_Static_Change_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (3 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Static_Change = {
	"Static-Change",
	"Static-Change",
	&asn_OP_BIT_STRING,
	asn_DEF_Static_Change_tags_1,
	sizeof(asn_DEF_Static_Change_tags_1)
		/sizeof(asn_DEF_Static_Change_tags_1[0]), /* 1 */
	asn_DEF_Static_Change_tags_1,	/* Same as above */
	sizeof(asn_DEF_Static_Change_tags_1)
		/sizeof(asn_DEF_Static_Change_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		&asn_JER_type_Static_Change_constr_1,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		BIT_STRING_constraint
	},
	0, 0,	/* No members */
	&asn_SPC_BIT_STRING_specs	/* Additional specs */
};

