/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103759BaseTypes"
 * 	found in "preprocessed_temp/EtsiTs103759BaseTypes.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/MRS_TS_103_759/Gen_File`
 */

#ifndef	_V2xPduStream_H_
#define	_V2xPduStream_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint8.h"
#include <asn_ioc.h>
#include "ObsPduEtsiGn.h"
#include "Ieee1609Dot2Data.h"
#include <ANY.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Certificate;

/* V2xPduStream */
typedef struct V2xPduStream {
	Uint8_t	 type;
	struct V2xPduStream__v2xPdus {
		A_SEQUENCE_OF(ANY_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} v2xPdus;
	struct Certificate	*certificate;	/* OPTIONAL */
	Uint8_t	 subjectPduIndex;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} V2xPduStream_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_V2xPduStream;
extern asn_SEQUENCE_specifics_t asn_SPC_V2xPduStream_specs_1;
extern asn_TYPE_member_t asn_MBR_V2xPduStream_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Certificate.h"

#endif	/* _V2xPduStream_H_ */
#include <asn_internal.h>
