/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103601Module"
 * 	found in "preprocessed_temp/EtsiTs103601Module.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/SDP_TS_103_601/Gen_File`
 */

#ifndef	_SequentialChunksSegmentedData_H_
#define	_SequentialChunksSegmentedData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequentialChunksSegmentedData */
typedef struct SequentialChunksSegmentedData {
	long	 messageSegmentTotalNumber;
	long	 thisMessageSegmentNumber;
	OCTET_STRING_t	 data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequentialChunksSegmentedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequentialChunksSegmentedData;
extern asn_SEQUENCE_specifics_t asn_SPC_SequentialChunksSegmentedData_specs_1;
extern asn_TYPE_member_t asn_MBR_SequentialChunksSegmentedData_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SequentialChunksSegmentedData_H_ */
#include <asn_internal.h>
