/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-Temp-Imports"
 * 	found in "preprocessed_temp/VAM-Temp-Imports.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IMZM_TS_103_724_NON_COMPLETO/Gen_File`
 */

#ifndef	_AreaRectangle_H_
#define	_AreaRectangle_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SemiRangeLength.h"
#include "WGS84AngleValue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OffsetPoint;

/* AreaRectangle */
typedef struct AreaRectangle {
	struct OffsetPoint	*nodeCenterPoint;	/* OPTIONAL */
	SemiRangeLength_t	 semiMajorRangeLength;
	SemiRangeLength_t	 semiMinorRangeLength;
	WGS84AngleValue_t	 semiMajorRangeOrientation;
	SemiRangeLength_t	*semiHeight;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AreaRectangle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AreaRectangle;
extern asn_SEQUENCE_specifics_t asn_SPC_AreaRectangle_specs_1;
extern asn_TYPE_member_t asn_MBR_AreaRectangle_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OffsetPoint.h"

#endif	/* _AreaRectangle_H_ */
#include <asn_internal.h>
