/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IMZM-PDU-Descriptions"
 * 	found in "preprocessed_temp/IMZM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IMZM_TS_103_724_NON_COMPLETO/Gen_File`
 */

#ifndef	_AreaEllipse_H_
#define	_AreaEllipse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SemiRangeLength.h"
#include "WGS84AngleValue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OffsetPoint;

/* AreaEllipse */
typedef struct AreaEllipse {
	struct OffsetPoint	*nodeCenterPoint;	/* OPTIONAL */
	SemiRangeLength_t	 semiMajorRangeLength;
	SemiRangeLength_t	 semiMinorRangeLength;
	WGS84AngleValue_t	 semiMajorRangeOrientation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AreaEllipse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AreaEllipse;
extern asn_SEQUENCE_specifics_t asn_SPC_AreaEllipse_specs_1;
extern asn_TYPE_member_t asn_MBR_AreaEllipse_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OffsetPoint.h"

#endif	/* _AreaEllipse_H_ */
#include <asn_internal.h>
