/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "preprocessed_temp/ISO-TS-19091-addgrp-C-2018.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IMZM_TS_103_724_NON_COMPLETO/Gen_File`
 */

#ifndef	_DSRC_HeadingConfidence_H_
#define	_DSRC_HeadingConfidence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSRC_HeadingConfidence {
	DSRC_HeadingConfidence_unavailable	= 0,
	DSRC_HeadingConfidence_prec10deg	= 1,
	DSRC_HeadingConfidence_prec05deg	= 2,
	DSRC_HeadingConfidence_prec01deg	= 3,
	DSRC_HeadingConfidence_prec0_1deg	= 4,
	DSRC_HeadingConfidence_prec0_05deg	= 5,
	DSRC_HeadingConfidence_prec0_01deg	= 6,
	DSRC_HeadingConfidence_prec0_0125deg	= 7
} e_DSRC_HeadingConfidence;

/* DSRC_HeadingConfidence */
typedef long	 DSRC_HeadingConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DSRC_HeadingConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DSRC_HeadingConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_DSRC_HeadingConfidence_specs_1;
asn_struct_free_f DSRC_HeadingConfidence_free;
asn_struct_print_f DSRC_HeadingConfidence_print;
asn_constr_check_f DSRC_HeadingConfidence_constraint;
ber_type_decoder_f DSRC_HeadingConfidence_decode_ber;
der_type_encoder_f DSRC_HeadingConfidence_encode_der;
xer_type_decoder_f DSRC_HeadingConfidence_decode_xer;
xer_type_encoder_f DSRC_HeadingConfidence_encode_xer;
jer_type_encoder_f DSRC_HeadingConfidence_encode_jer;
oer_type_decoder_f DSRC_HeadingConfidence_decode_oer;
oer_type_encoder_f DSRC_HeadingConfidence_encode_oer;
per_type_decoder_f DSRC_HeadingConfidence_decode_uper;
per_type_encoder_f DSRC_HeadingConfidence_encode_uper;
per_type_decoder_f DSRC_HeadingConfidence_decode_aper;
per_type_encoder_f DSRC_HeadingConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _DSRC_HeadingConfidence_H_ */
#include <asn_internal.h>
