/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IMZM-PDU-Descriptions"
 * 	found in "preprocessed_temp/IMZM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IMZM_TS_103_724_NON_COMPLETO/Gen_File`
 */

#ifndef	_InterferenceManagementMitigationType_H_
#define	_InterferenceManagementMitigationType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "MitigationForTechnologies.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InterferenceManagementMitigationType_PR {
	InterferenceManagementMitigationType_PR_NOTHING,	/* No components present */
	InterferenceManagementMitigationType_PR_unavailable,
	InterferenceManagementMitigationType_PR_mitigationForTechnologies
} InterferenceManagementMitigationType_PR;

/* InterferenceManagementMitigationType */
typedef struct InterferenceManagementMitigationType {
	InterferenceManagementMitigationType_PR present;
	union {
		NULL_t	 unavailable;
		MitigationForTechnologies_t	 mitigationForTechnologies;
	};
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterferenceManagementMitigationType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterferenceManagementMitigationType;
extern asn_CHOICE_specifics_t asn_SPC_InterferenceManagementMitigationType_specs_1;
extern asn_TYPE_member_t asn_MBR_InterferenceManagementMitigationType_1[2];
extern asn_per_constraints_t asn_PER_type_InterferenceManagementMitigationType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _InterferenceManagementMitigationType_H_ */
#include <asn_internal.h>
