/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "preprocessed_temp/ITS-Container.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IMZM_TS_103_724_NON_COMPLETO/Gen_File`
 */

#ifndef	_ITS_Container_SpeedConfidence_H_
#define	_ITS_Container_SpeedConfidence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ITS_Container_SpeedConfidence {
	ITS_Container_SpeedConfidence_equalOrWithinOneCentimeterPerSec	= 1,
	ITS_Container_SpeedConfidence_equalOrWithinOneMeterPerSec	= 100,
	ITS_Container_SpeedConfidence_outOfRange	= 126,
	ITS_Container_SpeedConfidence_unavailable	= 127
} e_ITS_Container_SpeedConfidence;

/* ITS-Container_SpeedConfidence */
typedef long	 ITS_Container_SpeedConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ITS_Container_SpeedConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_SpeedConfidence;
asn_struct_free_f ITS_Container_SpeedConfidence_free;
asn_struct_print_f ITS_Container_SpeedConfidence_print;
asn_constr_check_f ITS_Container_SpeedConfidence_constraint;
ber_type_decoder_f ITS_Container_SpeedConfidence_decode_ber;
der_type_encoder_f ITS_Container_SpeedConfidence_encode_der;
xer_type_decoder_f ITS_Container_SpeedConfidence_decode_xer;
xer_type_encoder_f ITS_Container_SpeedConfidence_encode_xer;
jer_type_encoder_f ITS_Container_SpeedConfidence_encode_jer;
oer_type_decoder_f ITS_Container_SpeedConfidence_decode_oer;
oer_type_encoder_f ITS_Container_SpeedConfidence_encode_oer;
per_type_decoder_f ITS_Container_SpeedConfidence_decode_uper;
per_type_encoder_f ITS_Container_SpeedConfidence_encode_uper;
per_type_decoder_f ITS_Container_SpeedConfidence_decode_aper;
per_type_encoder_f ITS_Container_SpeedConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ITS_Container_SpeedConfidence_H_ */
#include <asn_internal.h>
