/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "preprocessed_temp/VAM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IMZM_TS_103_724_NON_COMPLETO/Gen_File`
 */

#ifndef	_ItsPduHeaderVam_H_
#define	_ItsPduHeaderVam_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ITS-Container_ItsPduHeader.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ItsPduHeaderVam */
typedef ITS_Container_ItsPduHeader_t	 ItsPduHeaderVam_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ItsPduHeaderVam_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ItsPduHeaderVam;
asn_struct_free_f ItsPduHeaderVam_free;
asn_struct_print_f ItsPduHeaderVam_print;
asn_constr_check_f ItsPduHeaderVam_constraint;
ber_type_decoder_f ItsPduHeaderVam_decode_ber;
der_type_encoder_f ItsPduHeaderVam_encode_der;
xer_type_decoder_f ItsPduHeaderVam_decode_xer;
xer_type_encoder_f ItsPduHeaderVam_encode_xer;
jer_type_encoder_f ItsPduHeaderVam_encode_jer;
oer_type_decoder_f ItsPduHeaderVam_decode_oer;
oer_type_encoder_f ItsPduHeaderVam_encode_oer;
per_type_decoder_f ItsPduHeaderVam_decode_uper;
per_type_encoder_f ItsPduHeaderVam_encode_uper;
per_type_decoder_f ItsPduHeaderVam_decode_aper;
per_type_encoder_f ItsPduHeaderVam_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ItsPduHeaderVam_H_ */
#include <asn_internal.h>
