/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-Temp-Imports"
 * 	found in "preprocessed_temp/VAM-Temp-Imports.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IMZM_TS_103_724_NON_COMPLETO/Gen_File`
 */

#include "OffsetPoint.h"

static int
memb_nodeOffsetPointXY_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	//PROVA WITH COMPONENTS 
	// Tipo con vincolo: nodeOffsetPointXY
	// Accesso alla struttura tipizzata
	const nodeOffsetPointXY_t *typed_struct = (const nodeOffsetPointXY_t *)sptr;
	// Memorizzazione del tipo per uso successivo
	const char *constraint_type = "nodeOffsetPointXY";
	// Verifica del componente: node-LatLon (optional: no)
	/* Component node-LatLon is mandatory, cannot be absent */
	ASN__CTFAIL(app_key, td, sptr, "%s: Mandatory component 'node-LatLon' cannot be absent", td->name);
	return -1;
	// Verifica del componente: regional (optional: no)
	/* Component regional is mandatory, cannot be absent */
	ASN__CTFAIL(app_key, td, sptr, "%s: Mandatory component 'regional' cannot be absent", td->name);
	return -1;
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_nodeOffsetPointXY_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_nodeOffsetPointXY_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_OffsetPoint_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OffsetPoint, nodeOffsetPointXY),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NodeOffsetPointXY,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_nodeOffsetPointXY_constr_2,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_nodeOffsetPointXY_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_nodeOffsetPointXY_constraint_1
		},
		0, 0, /* No default value */
		"nodeOffsetPointXY"
		},
	{ ATF_POINTER, 1, offsetof(struct OffsetPoint, nodeOffsetPointZ),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NodeOffsetPointZ,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nodeOffsetPointZ"
		},
};
static const int asn_MAP_OffsetPoint_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_OffsetPoint_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_OffsetPoint_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nodeOffsetPointXY */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nodeOffsetPointZ */
};
asn_SEQUENCE_specifics_t asn_SPC_OffsetPoint_specs_1 = {
	sizeof(struct OffsetPoint),
	offsetof(struct OffsetPoint, _asn_ctx),
	asn_MAP_OffsetPoint_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_OffsetPoint_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_OffsetPoint = {
	"OffsetPoint",
	"OffsetPoint",
	&asn_OP_SEQUENCE,
	asn_DEF_OffsetPoint_tags_1,
	sizeof(asn_DEF_OffsetPoint_tags_1)
		/sizeof(asn_DEF_OffsetPoint_tags_1[0]), /* 1 */
	asn_DEF_OffsetPoint_tags_1,	/* Same as above */
	sizeof(asn_DEF_OffsetPoint_tags_1)
		/sizeof(asn_DEF_OffsetPoint_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_OffsetPoint_1,
	2,	/* Elements count */
	&asn_SPC_OffsetPoint_specs_1	/* Additional specs */
};

