/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-Temp-Imports"
 * 	found in "preprocessed_temp/VAM-Temp-Imports.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IMZM_TS_103_724_NON_COMPLETO/Gen_File`
 */

#ifndef	_OffsetPoint_H_
#define	_OffsetPoint_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NodeOffsetPointXY.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NodeOffsetPointZ;

/* OffsetPoint */
typedef struct OffsetPoint {
	NodeOffsetPointXY_t	 nodeOffsetPointXY;
	struct NodeOffsetPointZ	*nodeOffsetPointZ;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OffsetPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OffsetPoint;
extern asn_SEQUENCE_specifics_t asn_SPC_OffsetPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_OffsetPoint_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NodeOffsetPointZ.h"

#endif	/* _OffsetPoint_H_ */
#include <asn_internal.h>
