/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-Temp-Imports"
 * 	found in "preprocessed_temp/VAM-Temp-Imports.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IMZM_TS_103_724_NON_COMPLETO/Gen_File`
 */

#ifndef	_VAM_Temp_Imports_BasicContainer_H_
#define	_VAM_Temp_Imports_BasicContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VAM-Temp-Imports_StationType.h"
#include "ReferencePosition.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VAM-Temp-Imports_BasicContainer */
typedef struct VAM_Temp_Imports_BasicContainer {
	VAM_Temp_Imports_StationType_t	 stationType;
	ReferencePosition_t	 referencePosition;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VAM_Temp_Imports_BasicContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VAM_Temp_Imports_BasicContainer;

#ifdef __cplusplus
}
#endif

#endif	/* _VAM_Temp_Imports_BasicContainer_H_ */
#include <asn_internal.h>
