/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-Temp-Imports"
 * 	found in "preprocessed_temp/VAM-Temp-Imports.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IMZM_TS_103_724_NON_COMPLETO/Gen_File`
 */

#ifndef	_VAM_Temp_Imports_ItsPduHeader_H_
#define	_VAM_Temp_Imports_ItsPduHeader_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "StationID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VAM_Temp_Imports_ItsPduHeader__messageID {
	VAM_Temp_Imports_ItsPduHeader__messageID_denm	= 1,
	VAM_Temp_Imports_ItsPduHeader__messageID_cam	= 2,
	VAM_Temp_Imports_ItsPduHeader__messageID_poi	= 3,
	VAM_Temp_Imports_ItsPduHeader__messageID_spatem	= 4,
	VAM_Temp_Imports_ItsPduHeader__messageID_mapem	= 5,
	VAM_Temp_Imports_ItsPduHeader__messageID_ivim	= 6,
	VAM_Temp_Imports_ItsPduHeader__messageID_ev_rsr	= 7,
	VAM_Temp_Imports_ItsPduHeader__messageID_tistpgtransaction	= 8,
	VAM_Temp_Imports_ItsPduHeader__messageID_srem	= 9,
	VAM_Temp_Imports_ItsPduHeader__messageID_ssem	= 10,
	VAM_Temp_Imports_ItsPduHeader__messageID_evcsn	= 11,
	VAM_Temp_Imports_ItsPduHeader__messageID_saem	= 12,
	VAM_Temp_Imports_ItsPduHeader__messageID_rtcmem	= 13,
	VAM_Temp_Imports_ItsPduHeader__messageID_vam	= 14
} e_VAM_Temp_Imports_ItsPduHeader__messageID;

/* VAM-Temp-Imports_ItsPduHeader */
typedef struct VAM_Temp_Imports_ItsPduHeader {
	long	 protocolVersion;
	long	 messageID;
	StationID_t	 stationID;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VAM_Temp_Imports_ItsPduHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VAM_Temp_Imports_ItsPduHeader;

#ifdef __cplusplus
}
#endif

#endif	/* _VAM_Temp_Imports_ItsPduHeader_H_ */
#include <asn_internal.h>
