/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-Temp-Imports"
 * 	found in "preprocessed_temp/VAM-Temp-Imports.asn"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -D /home/fdg/Scrivania/FinalTest/IMZM_TS_103_724_NON_COMPLETO/Gen_File`
 */

#ifndef	_VAM_Temp_Imports_StationType_H_
#define	_VAM_Temp_Imports_StationType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VAM_Temp_Imports_StationType {
	VAM_Temp_Imports_StationType_unknown	= 0,
	VAM_Temp_Imports_StationType_pedestrian	= 1,
	VAM_Temp_Imports_StationType_cyclist	= 2,
	VAM_Temp_Imports_StationType_moped	= 3,
	VAM_Temp_Imports_StationType_motorcycle	= 4,
	VAM_Temp_Imports_StationType_passengerCar	= 5,
	VAM_Temp_Imports_StationType_bus	= 6,
	VAM_Temp_Imports_StationType_lightTruck	= 7,
	VAM_Temp_Imports_StationType_heavyTruck	= 8,
	VAM_Temp_Imports_StationType_trailer	= 9,
	VAM_Temp_Imports_StationType_specialVehicles	= 10,
	VAM_Temp_Imports_StationType_tram	= 11,
	VAM_Temp_Imports_StationType_lightVruVehicle	= 12,
	VAM_Temp_Imports_StationType_animal	= 13,
	VAM_Temp_Imports_StationType_roadSideUnit	= 15
} e_VAM_Temp_Imports_StationType;

/* VAM-Temp-Imports_StationType */
typedef long	 VAM_Temp_Imports_StationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VAM_Temp_Imports_StationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VAM_Temp_Imports_StationType;
asn_struct_free_f VAM_Temp_Imports_StationType_free;
asn_struct_print_f VAM_Temp_Imports_StationType_print;
asn_constr_check_f VAM_Temp_Imports_StationType_constraint;
ber_type_decoder_f VAM_Temp_Imports_StationType_decode_ber;
der_type_encoder_f VAM_Temp_Imports_StationType_encode_der;
xer_type_decoder_f VAM_Temp_Imports_StationType_decode_xer;
xer_type_encoder_f VAM_Temp_Imports_StationType_encode_xer;
jer_type_encoder_f VAM_Temp_Imports_StationType_encode_jer;
oer_type_decoder_f VAM_Temp_Imports_StationType_decode_oer;
oer_type_encoder_f VAM_Temp_Imports_StationType_encode_oer;
per_type_decoder_f VAM_Temp_Imports_StationType_decode_uper;
per_type_encoder_f VAM_Temp_Imports_StationType_encode_uper;
per_type_decoder_f VAM_Temp_Imports_StationType_decode_aper;
per_type_encoder_f VAM_Temp_Imports_StationType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VAM_Temp_Imports_StationType_H_ */
#include <asn_internal.h>
